### ISSUE TITLE
Duda p2 parte b) T1

### ISSUE THREAD

**Issue by MatiLaB** [IIC1253/IIC1253-2024-1#10]
Hola, con respecto a la parte b) del problema 2: 
<img width="347" alt="T1 p2 b)" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141693762/c4a89196-80f6-45c8-97d4-ed055710b180">

Quería saber si es necesario encontrar un valor para a, como que dependa de n o k tal vez, o (como yo lo interpreté) que se asume que es un natural cualquiera. En el segundo caso, con llegar a algo de la forma F(n) * natural, sería valido? El valor de a debería variar dependiendo del valor de k, por lo que me hace sentido que con eso se pueda demostar. Pero igual quedo con la duda porque normalmente buscamos llegar a la igualdad pedida, en este caso F(kn) = aF(n).

**Comment by seba-bug** [comment]
Hola!
El a es un factor que muestra que F(nk) es múltiplo de F(n). No nos interesa realmente cuanto vale. En tu hipótesis inductiva asumirás que k cumple que existe un a tal que F(nk)=aF(n) (no sabemos cuánto vale a) y tienes que demostrar que para un k más grande también existe un factor adecuado (no es el mismo, pero tampoco nos interesa realmente cuánto vale exactamente). Muy probablemente te quedará que el nuevo factor es una formulita que usa el a que asumiste que existe.
Abrazo

**Comment by jorgee02** [comment]
Hola profe, buenas tardes. En ese sentido, quisiera preguntarle si es incorrecto que el factor que acompaña a F(n) al demostrar para F((k+1)n) dependa de k de alguna manera. Intuitivamente, me parece que debería depender de k, dado que conforme crezca k, el factor de F(n) debería crecer. 
Espero su respuesta, gracias :D

**Comment by fvaldes17** [comment]
@jorgee02 Fíjate que el enunciado menciona "para todo k >=1 y n >= 0 existe un natural a tal que ...". Esto implícitamente (o no) dice que a depende tanto de k como de n, es decir, a puede tomar diferentes valores dependiendo del par (k,n). En este sentido es completamente válido que el factor que acompaña a F(n) dependa de k, aún en el paso inductivo. Se entiende bien el por qué?

**Comment by jorgee02** [comment]
Sip, muchas gracias!

**Comment by tremendapithon** [comment]
El caso de la pregunta 2b, puedo usar induccion simple y el principio del inciso a???

**Comment by fvaldes17** [comment]
Si puedes! 🤓
