### ISSUE TITLE
Demostración por contradicción

### ISSUE THREAD

**Issue by santiago3c** [IIC1253/IIC1253-2024-1#100]
Hola, en el ejercicio que adjunto, no se puede decir que me doy como dominio un conjunto con un único elemento, por ejemplo el {1}, y así simplemente me queda F(x,y,z) en un lado y - F(x, y, z) en el otro?
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/142272696/808c0122-58a1-4641-82e2-c51ef6b2c107)

**Comment by PaulaGrune** [comment]
Hola! El contra ejemplo puede ser cualquier interpretación que encuentres tal que no cumpla la equivalencia lógica. En el ejemplo que mencionas te falta darle una interpretación al predicado F, para que la demostración sea válida.

**Comment by santiago3c** [comment]
gracias, entonces sirve si digo dom: {1} y F(x,y,z) := x+y+z=3

**Comment by PaulaGrune** [comment]
Si! Pero en ese caso también deberás definir los símbolos +, = y el 3 (para poder usarlos en el predicado)

**Comment by santiago3c** [comment]
entendido, gracias!

**Comment by luzmagurzua** [comment]
Holaa, aquí como sería para demostrarlo sin contraejemplo?
