### ISSUE TITLE
Ejercicio semáforos

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#101]
Hola! Estaba revisando la pauta de la tarea 2, y me surgió una duda para definir b). Entiendo como construyen la formula, sin embargo me pregunto si la siguiente servirá igual? (intenté ver si eran equivalentes, sin embargo no llegué a nada...) 

$$\bigwedge_{t=1}^{T} \Big( (v_t \rightarrow (a_{t+1} \land \neg r_{t+1})) \lor (a_t \rightarrow (r_{t+1} \land \neg v_{t+1})) \lor (r_t \rightarrow (v_{t+1} \land \neg a_{t+1})) \Big)$$

que sería básicamente, si la luz es verde, el siguiente semáforo mostrará luz amarilla y no roja, 
o si la luz es amarilla, en el siguiente semáforo se mostrará luz roja y no verde, 
o si la luz es roja, se mostrará la luz verde y no amarilla.

**Comment by pibahamondesw** [comment]
No es equivalente. Nótese que esa fórmula es satisfactible con la valuación que hace falsas a todas las variables, pues todas las implicancias serían verdaderas con sus antecedentes falsos.

**Comment by luzmagurzua** [comment]
Entiendo! Gracias. O sea no se podría representar en una sola fórmula las dos condiciones que piden, mejor siempre descomponerlo en dos partes para no entrar en algún error
