### ISSUE TITLE
Logica de predicados, simbolos que no necesitan una interpretacion explicita

### ISSUE THREAD

**Issue by bugfly1** [IIC1253/IIC1253-2024-1#102]
En lógica de predicados, ¿Los únicos símbolos de los cuales se conoce el significado son los operadores lógicos (¬, ^,u,->, <->), los parentesis y los cuantificadores, verdad?
¿Todos los demás símbolos que se utilicen necesitan que se le entregue alguna interpretación o hay alguno mas que tengamos que tener en mente?

**Comment by pibahamondesw** [comment]
Me parece que en ayudantías/tareas quedan mencionados también XOR y NAND, que no necesitarían una explicación adicional, pero no vimos todo el montón de propiedades para las fórmulas como asociatividad, conmutatividad, equivalencias... Es razonable asumir esos operadores por simplicidad para todo.
