### ISSUE TITLE
Ejercicio 1 ayudantía 4

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC1253/IIC1253-2024-1#103]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/101026528/0ebbcb3b-1d26-4927-a946-b17acaffb9c6)
Quería consultar si está bien esta Demostración por contrapositivo, es para la dirección de derecha a izquierda del si y solo si

**Comment by pibahamondesw** [comment]
A priori, yo diría que está bien encaminada pero incompleta. Algunos comentarios:
- ¿De dónde sacas que tu interpretación satisface a \Sigma?
- Más importante, ¿de dónde sacas esa interpretación?
- Estás abusando del símbolo de equivalencia en la última línea
- Te falta pasar de la última línea a que el conjunto con las fórmulas de \Sigma y la negación de \varphi es consistente (es trivial, pero necesario para concluir, es consistente porque esa interpretación que mencionas es la que satisface al conjunto).

**Comment by BenzoylMorexide** [comment]
Para el primer punto, comprendo que asumí mal ahí. Ahora estaba intentado hacerlo de nuevo pero me surgió una duda. Si sigma no satisface a phi, puedo decir que la interpretación satisface a sigma pero no satisface a phi? o debo considerarlo como lo hice ahí, diciendo que puede ocurrir que la interpretación no satisfaga a phi O no satisfaga a Sigma.}
Gracias!
