### ISSUE TITLE
disyunción

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#105]
Puedo separar valuaciones cuando hay una disyunción dentro de ellas? por ejemplo con V valuación de la otra cosa, v una disyunción, 
V(lambda v theta) = 1
Podría separarlo en
V(lambda) o V(theta)
como diciendo que se tiene que cumplir la valuación para uno de los dos?

**Comment by pibahamondesw** [comment]
Más bien en V(lambda)=1 o V(theta)=1, pero sí. Revisa la definición inductiva que hicimos de la valuación de una fórmula y es prácticamente eso mismo.
