### ISSUE TITLE
Consecuencia logica i2022

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#106]
Esto sale en un solucionario de la i del 2022-1: **Como Σ es no redundante tenemos que Σ⧹{α} ⊭ α, esto significa que existe v tal que satisface Σ⧹{α} pero α(v) = 0.** Pero porque podemos decir que existe ese v? En otra issue me respondieron que si algo no era consecuencia logica de un conjunto era porque ninguna valuacion satisface al conjunto y a ese algo al mismo tiempo. Esto de podia deber a tres cosas: las valuaciones que hacen vd al conjunto no hacen vd a ese algo, ninguna valuacion hace vd al conjunto, ninguna valuacion hace vd a ese algo, o ambas. Pero aca en solucionario dicen que existe una valuacion v que satisface al conjunto, pero segun yo eso no necesariamente es verdad. Puede que ninguna valuacion satisfaga a Σ⧹{α} .

**Comment by pibahamondesw** [comment]
No sé si typo tuyo o de la I, pero debería haber sido v(α) = 0, no α(v) = 0.

Pero respondiendo a la pregunta, suponiendo que Σ no es inconsistente, viene de la definición de consecuencia lógica. Nota que Σ⧹{α} ⊭ α es la negación de que Σ⧹{α} ⊨ α, y eso a su vez es la negación de que para toda valuación v, si v(Σ⧹{α}) = 1, entonces v(α) = 1. O sea, que existe una valuación v tal que v(Σ⧹{α}) = 1 y v(α) = 0.

**Comment by sopadeoliva** [comment]
Hola! Para complementar la respuesta:

1. La definición de consecuencia lógica no es exactamente la que dices. Si tenemos $\Sigma \vDash \alpha$ significa que *toda valuación que satisfaga a* $\Sigma$ *también debe satisfacer a* $\alpha$. Por lo tanto, si tenemos una valuación $\sigma_1$ tal que $\sigma_1(\Sigma)=1$ y $\sigma_1(\alpha)=1$ (satisface ambos), PERO además tenemos otra valuación $\sigma_2$ tal que $\sigma_2(\Sigma)=1$ y $\sigma_2(\alpha)=0$ (satisface al conjunto pero no a $\alpha$, entonces $\Sigma \nvDash \alpha$. En este caso existe una valuación que satisface a ambos, pero no se cumple para toda valuación. Por eso no es consecuencia lógica.
2. Si no existe valuación que satisfaga a $\Sigma$ a este se le llama insatisfacible (es inconsistente). En este caso **toda fórmula es consecuencia lógica de** $\Sigma$. Esto puede ser un poquito menos intuitivo, pero piensa en la consecuencia como una implicancia (Si una valuación satisface a $\Sigma \longrightarrow$ esta misma satisface a $\alpha$). En el caso de que no exista valuación, la primera parte de esta implicancia siempre es falsa, y por lo tanto, trivialmente, la implicancia entera es verdadera: $\Sigma \vDash \alpha$.  

En tu caso particular, si decimos que $\Sigma – \{\alpha\} \nvDash \alpha$, debe existir alguna valuación que satisfaga a $\Sigma – \{\alpha\}$ ya que, si no la hubiese, toda fórmula sería consecuencia lógica de este conjunto y, en particular, $\Sigma – \{\alpha\} \vDash \alpha$.

Espero que te haya ayudado! Saludos 🐸
