### ISSUE TITLE
Duda requisito tareas

### ISSUE THREAD

**Issue by Amegonzale** [IIC1253/IIC1253-2024-1#11]
Holi buenas. Tengo una duda sobre este punto en particular "Cada solución de cada problema debe comenzar en una nueva hoja. Hint: Utilice \newpage", debo hacer una nueva hoja por cada inciso (a, b, c) o por cada pregunta (1, 2)? La pregunta es muy basica pero no me quiero equivocar en eso jiji. Muchas gracias!

**Comment by seba-bug** [comment]
Hola Amegonzale
Es por pregunta, no inciso
Abrazo
