### ISSUE TITLE
Mega conjunción y disyunción

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#110]
Cuando ocupamos la notación de la disyunción grande que va desde i=1 hasta i=n por ejemplo, puedo agregarle una restricción del tipo i != j bajo el símbolo, como diciendo que quiero la conjunción de aquellos que cumplen eso, si estoy evaluando para j, por ejemplo?

**Comment by sopadeoliva** [comment]
Hola!

Sí puedes hacer eso :) es suficiente con colocar la desigualdad $i \neq j$ debajo del $i = 1$, o separados por una coma, tú elige 👍
