### ISSUE TITLE
Dominio de la interpretación

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#111]
En la pregunta 2a, qué dominio debemos asumir que tiene la interpretación dada? porque nos hablan del = pero no del dominio, y la satisfacibilidad va a depender del dominio de interpretación. Y, además, esto tiene relación con la pregunta 1 o los predicados solo tienen el mismo nombre?

**Comment by sopadeoliva** [comment]
Hola! 

Si quieres mostrar que una formula es satisfacible tienes que proponer alguna interpretación y mostrar que la satisfaga: esto implica proponer tú un dominio y un "significado" de los predicados. Esta parte de la pregunta no tiene relación con la P1.

Muchos éxito!🐸
