### ISSUE TITLE
Duda sobre como demostrarlo. a)

### ISSUE THREAD

**Issue by Mardones567** [IIC1253/IIC1253-2024-1#112]
Hola tengo una duda sobre 2a), basta con explicar con palabras porque no es satisfacible o existe una demostración más formal sobre estos enunciados?

**Comment by tremendapithon** [comment]
En la 2a) debo demostrar o dar un contra ejemplo??

**Comment by sopadeoliva** [comment]
Entre esta respuesta y la issue #111 debería quedar más claro qué hacer: depende si demuestras que es satisfacible o no.
