### ISSUE TITLE
Orden de operaciones lógicas

### ISSUE THREAD

**Issue by m-cozzetti** [IIC1253/IIC1253-2024-1#115]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/167556395/8bedcd87-b752-434c-bfdd-3264198d3670)
Aqui se debe tomar como (D y G) -> (etc.) o como D y (G -> (etc.))? Esta expresion es ambigua o existe un orden de operaciones estandar para los operadores lógicos?

**Comment by sopadeoliva** [comment]
Revisa la issue #81 !
