### ISSUE TITLE
Cómo definir un predicado bajo una interpretación formalmente

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC1253/IIC1253-2024-1#117]
Buenas tardes. ✨

Revisando evaluaciones anteriores, y la Tarea 3, me han surgido dudas respecto de cuál es la forma correcta o qué diferencias tiene definir los predicados bajo una interpretación de alguna de las siguientes dos formas:

- Primera forma: 
  ![image](https://github.com/IIC1253/IIC1253-2024-1/assets/30756770/3b40e107-31e6-4b12-b654-67dc125f4f7d)

- Segunda forma:
  ![image](https://github.com/IIC1253/IIC1253-2024-1/assets/30756770/b2eee6fa-96a6-4476-a1be-ee93e98f4584)

Siento que la primera forma es más "intuitiva", mientras que la segunda forma la siento menos "intuitiva" y no sé si hay alguna diferencia sustancial entre ambas 😓

**Comment by c4ebt** [comment]
Hola!

Ambas formas son correctas formalmente. Estoy de acuerdo contigo, en mi opinión la primera es más intuitiva y también se ve un poco más formal, pero en general no se requiere mucho rigor en cuanto a la notación con la que se definen predicados, por lo que ambas formas se consideran correctas.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Muchas gracias ✨🍀
