### ISSUE TITLE
Casos base en Inducción Fuerte

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC1253/IIC1253-2024-1#12]
Hola!

Estaba releyendo los contenidos de inducción fuerte y me entró una duda sobre los casos base en esta inducción. Lo que no termino de comprender es _**cómo determinar los casos base para la inducción fuerte.**_ En las diapositivas de clase veo que esto se plantea como preguntas en las "pastillitas azules", por lo que creo que no debí anotar en clase lo que se dijo 🥹

Por ejemplo, al demostrar que $$F(n) < 2^n$$ en las diapositivas, se emplean 2 casos base, lo cual (creo) se debe a la naturaleza de la definición de la sucesión de Fibonacci, pues toma la suma de los dos antecesores previos. En este contexto, ¿la cantidad de casos base dependerá de cómo yo vaya a demostrar (usando uno, dos, tres o más antecesores), o simplemente de la naturaleza de la "función" (cuántos antecesores emplee esta en su definición)?

**Comment by PaulaGrune** [comment]
Hola!
Para determinar la cantidad de casos bases es necesario que revises cuántos casos se utilizan en la definición de la función. En el ejemplo que entregas, Fibonacci se define como la suma de dos números antecesores, por lo que la demostración requerirá dos casos base

**Comment by Pablo-Gonzalez-Calderon** [comment]
Ahhh, comprendo.

Muchas gracias ✨
