### ISSUE TITLE
Satisfacibilidad en lógica de predicados

### ISSUE THREAD

**Issue by k0rval4n** [IIC1253/IIC1253-2024-1#121]
¡Hola! Luego de revisar las clases y la issues #78 y #111 me queda la duda. En lógica proposicional una fórmula es satisfacible cuando al menos una valuación la hace verdadera, y es no satisfacible cuando ninguna valuación hace verdadera a la fórmula. ¿Esto es extrapolable a lógica proposicional? Es decir, que un predicado es satisfacible cuando al menos una interpretación permite satisfacerlo (vasta con proponer una interpretación que permita satisfacer al predicado), y es no satisfacible cuando ninguna interpretación permite satisfacer al predicado (es necesario demostrar que ninguna interpretación puede satisfacerlo).

Esperando atentamente su respuesta, me despido. ¡Muchas gracias!

**Comment by BenzoylMorexide** [comment]
Respondo por mientras, y que luego un ayudante confirme. Sí, tengo entendido que las valuaciones y las interpretaciones son análogas en ese sentido.

**Comment by c4ebt** [comment]
Hola! Efectivamente, esa es la noción de satisfacibilidad en lógica de predicados.
