### ISSUE TITLE
p1.d Duda creación de nuevo cuantificador 

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC1253/IIC1253-2024-1#123]
Hola! encontré una manera de definir al cuantificador existencial único con los predicados que tenemos dados en la p1. ¿Es legal definir al cuantificador existencial único, siempre y cuando esté utilizando cosas dadas? Lo que busco hacer, para dar más contexto, es decir que para cada valor z en cada diagonal, existe exactamente una celda con índices (x,x) en diagonal principal y (x,y) en la secundaria al que ese z puede estar asignado, como una suerte de biyectividad,

Gracias!

**Comment by fvaldes17** [comment]
Holii!

Si pueden definir esta variante del cuantificador existencial, siempre que demuestren por qué la definición que dan del cuantificador implica lo que buscan, es decir, deben demostrar por qué su nuevo cuantificador se interpreta como "existe un único ...". Esto es en general, es decir, pueden definir predicados auxiliares utilizando los predicados y la interpretación dada en el enunciado siempre que lo necesiten, pero demostrando la validez del predicado en cada caso :)

Éxito! 🌠
