### ISSUE TITLE
Duda sobre el n0 dependiendo de k. P1 c)

### ISSUE THREAD

**Issue by aangel-sama** [IIC1253/IIC1253-2024-1#13]
Hola, haciendo la parte c de la pregunta 1, quise encontrar una relacion entre el n0 y el k, mi duda es si necesariamente la relacion entre ambos nos tiene que dar el menor numero de n0 para que se cumpla para algun k, por ejemplo, para un k=1, el n0 puede partir del 0, para un k=2, el n0 parte del 5, para un k=3 el n0 parte del 10, para un k=4 el n0 parte del 17, ahora bien, si mi relacion hace que el n0 para el k1 parta del 2, o si el n0 para un k=2 parta del 6, funciona? o nos tiene que dar justo esos valores?

**Comment by seba-bug** [comment]
Hola!
Basta con cualquier n0 adecuado que funcione, no se pide el menor. Efectivamente, si conoces uno en específico, cualqueira más grande también funciona. La idea es que sea un función de k que cumpla lo pedido no más.
Un abrazo
