### ISSUE TITLE
Pregunta en la parte (c)

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#132]
Se nos indica $\sim_1 \subseteq \sim \subseteq \sim_2$. ¿Es válido decir que puede pasar que $\sim_1 = \sim_2 = \sim_3$? Pues en ningún lugar se nos dice que deben ser distintas.

**Comment by AndreaPGS** [comment]
Holis, A ⊆ B significa que A está contenido en B o es igual a B, por lo que puede ocurrir el caso que mencionas. Lo importante es que la propiedad pedida se cumpla **para toda relación de equivalencia en A** siendo ∼<sub> 1</sub> y ∼<sub> 2</sub> también relaciones de equivalencia.

**Comment by k0rval4n** [comment]
> Holis, A ⊆ B significa que A está contenido en B o es igual a B, por lo que puede ocurrir el caso que mencionas. Lo importante es que la propiedad pedida se cumpla **para toda relación de equivalencia en A** siendo ∼ 1 y ∼ 2 también relaciones de equivalencia.

Basándome en esto, ¿puedo definir (∼1 = ∼) o (∼2 = ∼)? (Lo cual me deja un ∼1 o ∼2 que no son fijos, varían al variar ∼)
