### ISSUE TITLE
Definicion de la relación menor en la parte a)

### ISSUE THREAD

**Issue by PelayoF** [IIC1253/IIC1253-2024-1#133]
Hola, para la definicion de la relación $\prec$ no debiese estar ésta definida con un "menor igual" para que se pueda cumplir las propiedades de una relacion de orden parcial.

Saludos.

**Comment by luzmagurzua** [comment]
Estamos con la misma duda en la issue #131

**Comment by PelayoF** [comment]
Ok, no la había visto.
Gracias
