### ISSUE TITLE
Duda parte C

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#134]
Hola,
En la tarea se nos pide generalizarlo para $\mathbb{N}^k$. No entiendo si esto significa que ahora se tratarán tuplas con $k$ elementos $(a_1,a_2,...,a_k)$ y como la definición solo toma en cuenta $a_1, a_2$, los demás no nos importarían, o si se refiere a la definición de tuplas de tuplas, como $(a, (b, (c, (e, ...))))$, y en la definición se cambia $<$ y $\leq$ por $\preceq$.

Agradezco mucho su atención.

**Comment by MIrarrazaval** [comment]
Hola! La pregunta se refiere a tu primera definición de tuplas. La idea es que definas una nueva relación, similar a la que ya te entregamos, que sí considere todas las k entradas. Saludos!
