### ISSUE TITLE
t1 p2 b)

### ISSUE THREAD

**Issue by JSalas277** [IIC1253/IIC1253-2024-1#14]
![egfm](https://github.com/IIC1253/IIC1253-2024-1/assets/131331665/204018dc-7565-4a0a-a4e8-903d9650f5c0)

Tengo un problema acerca de la a, tiene que tener algún tipo de cambio o solo necesito considerarlo como algo constante como n?
Ademas, si necesito considerar el inciso a), entonces hay que usarla en la tesis inductiva, pero sera posible sin tener un +1 en F(kn + n)?

**Comment by seba-bug** [comment]
Hola!
En el 2b buscamos demostrar que F(kn) es múltiplo de F(n) para cualquier elección de k y n. El "a" es el factor que aparece para mostrar que efectivamente es múltiplo. Entonces, para demostrar lo pedido te sugerimos hacer inducción sobre k, asumiendo que el n es fijo. ¿Qué pasa con el a? No necesariamente el factor a en F(kn) = aF(n) es el mismo que en F((k+1)n) = bF(n) (de hecho, no es el mismo porque necesita ser más grande). Realmente no nos interesa quién sea, lo importante es que muestres que existe un número b que cumple eso. Al hacer tu desarrollo debieras llegar a una factorización del estilo b*F(n).

El desafío es ver cómo descomponer el término F(kn) para usar tu hipótesis inductiva, y ahí viene útil la propiedad 2a. ¿Qué nos enseña a hacer la 2a? Asegúrate de entender qué hace la propiedad 2a porque eso te permitirá descomponer. No es obligación usarlo, pero simplifica la misión.

Un abrazo

**Comment by tremendapithon** [comment]
Para el 2b, no veo la necesidad de usar inducción fuerte, se puede realizar con induccion simple y en la HI asumir que la propiedad se cumple para "n' y en TI demostrar para "n+1" (paso donde podria usar la propiedad (a)) o debo hacerlo con induccion fuerte?  

Saludos
