### ISSUE TITLE
Duda pauta ayudantía 7: "Los enteros son un orden total"

### ISSUE THREAD

**Issue by Anton-Little** [IIC1253/IIC1253-2024-1#143]
Hola, en la pauta de la ayudantía 7 dice lo siguiente:
<img width="790" alt="image" src="https://github.com/IIC1253/IIC1253-2024-1/assets/127431512/2143b732-d067-4bf8-a762-100486504721">
Estoy muy confundido, ¿como los enteros son un orden total? Yo tenía entendido que los conjuntos de pares ordenados eran relaciones que podían ser órdenes, ¿acaso los enteros también son conjuntos de pares ordenados :O?

Gracias de antemano :)

**Comment by Maratripa** [comment]
Hola! Es un error de tipeo de la solución, se refiere a que la relación menor o igual (<=) es un orden total **sobre** el conjunto de los enteros.
