### ISSUE TITLE
Referencias en tareas

### ISSUE THREAD

**Issue by lietril** [IIC1253/IIC1253-2024-1#15]
Holaa, para una pregunta de la tarea utilizé de referencia un ejercicio y una explicación del ppt visto en clase. ¿Es necesario referenciarlo? _(Y si es necesario, ¿cómo lo incluyo en el documento?)_

**Comment by seba-bug** [comment]
Hola lietril
Nos interesa que la referencia permita a los ayudantes acceder a tu fuente. Si es del material de clase basta decir "como se vio en X diapo de la clase Y". Si es un recurso externo al material del curso, es importante un link para poder acceder (y tiene que ser accesible por el equipo de ayudantes, es decir, no aceptamos páginas pagadas que resuelven problemas).

**Comment by Yeps3nM** [comment]
Hola! 

Yo también tengo duda respecto al alcance de las referencias, en qué minuto necesito yo decir que usé algún material externo? Porque revisé videos y resoluciones que daban problemas similares a los que yo necesitaba pero no son lo mismo. Debo decir que usé guía de ellos? Mencionar explícitamente si usé algún truco igual? Gracias :)

**Comment by seba-bug** [comment]
Hola!
Como primera idea, no se compliquen demasiado con esto... en caso de dudas, pongan el link en su tarea. Lo que nos interesa es que aprendar al hacer las tareas. Es super legal revisar otros recursos, videos, etc.

Ahora, como explicamos en clase, el motivo de pedir referencias es

1. Si usas una secuencia de pasos, truco o la demostración entera de algún recurso externo al curso. Ej: llevo pegado 2 días y logré resolver una demo con una muy similar que encontré. Obviamente, tu desarrollo de la pregunta entera no puede ser completamente igual a algo que encontraste, porque nos interesa que lo hagas con tus palabras, entendiendo lo que sucede. Referenciar y poner la misma exacta demo que encontraste se evalúa con 1.0 porque no la asimilaste. 
2. Para descartar casos de copia entre estudiantes. Si dos personas hicieron una demostración con la misma estructura lógica o usaron un truco idéntico que no vimos en clases o en los materiales del curso y no referenciaron una fuente, es sospechoso.

Da lo mismo realmente el formato de la referencia, lo importante es poder acceder a ella. 
Abrazo
