### ISSUE TITLE
Como saber que necesito más de un caso base?

### ISSUE THREAD

**Issue by Tichi1010** [IIC1253/IIC1253-2024-1#16]
Hola buenas, mi duda es ¿Como saber que necesito más de un caso base?
En el ejemplo que dio el profe Bugedo en clases en donde teníamos que demostar que F(n) <= 2^n para todo n, tenemos dos casos bases F(0) y F(1), ¿Eso de debe a como estan definidos F(0) y F(1) en Fibonacci (que no ocupan la fórmula)? o se debe a ¿Como está definido Fibonacci, que se forma a partir de los dos casos anteriores y por lo tanto necesitaria dos casos bases?

**Comment by seba-bug** [comment]
Hola Tichi1010
Hay que tener ojo con lo de los casos base. Quién nos dice cuántos necesitamos es la propiedad que queremos demostrar. Dada la propiedad P(n), nos tenemos que preguntar ¿hay algún valor de n que no dependa de otros valores de n más pequeños? Tales valores serán casos base. En el ejemplo que vimos en clase, la propiedad es 
P(n) := "F(n) <= 2^n"
¿Qué casos no requieren valores anteriores? El n=4 sí requiere porque F(4) no es un caso base de la fórmula de Fibonacci. En cambio, n=0 y n=1 los podemos hacer simplemente insertando los casos base de Fibonacci.
 
Mi consejo es no mecanizar que "siempre habrá 2 casos base en Fibonacci", porque eso dependerá de la propiedad que estemos trabajando (podría ser 1 o más de 2 en algunas propiedades más raras). ¿Se entiende?

**Comment by pibahamondesw** [comment]
Sumándome a Seba, creo que se vuelve más intuitivo con la inducción estructural. Fíjate que la sucesión de Fibonacci F(n) para n natural, se puede definir estructuralmente como:
1) F(0) = 0
2) F(1) = 1
3) Si F(n-2) y F(n-1) son términos de Fibonacci, entonces F(n) = F(n-1) + F(n-2) (para n>=2)
Los casos (1) y (2) son los casos base, que usualmente requerirán ser demostrados como casos base en una inducción estructural, mientras que el (3) define la regla de construcción a partir de casos anteriores, lo que usualmente se convertirá en un paso inductivo.

De forma general, me atrevería a decir que los casos base de tu estructura definida de forma inductiva te servirán de casos base para la inducción y cada regla de construcción te servirá para el paso inductivo. Finalmente, en ciertas situaciones, te podrías encontrar que es más fácil definir algunos casos base adicionales que te permitirán utilizar propiedades intermedias para que la demostración sea más fácil (por ejemplo, simplificando desigualdades).
