### ISSUE TITLE
Duda Cardinalidad guia i2 pregunta 2

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#166]
¿es verdad que la union de varios conjuntos enumerables es numerable?
¿Se puede usar eso en la prueba si fuera verdad?

**Comment by c4ebt** [comment]
Hola! Sí, ese resultado es correcto. No te puedo asegurar que puedas usar eso en la prueba así tal cual, pero mi recomendación es que entiendas como demostrarlo y puedas aplicarlo, para que te sirva como una potencial herramienta para la prueba.

**Comment by pibahamondesw** [comment]
No exactamente. La unión finita o infinita enumerable de conjuntos enumerables es efectivamente enumerable. La demostración para el caso de unión finita (que recomiendo fuertemente que hagas) es más o menos similar a la que vimos en clase para $\mathbb{N}^n$. Para el caso de unión infinita enumerable hay que ponerse un poco más creativos, pero sigue una suerte de generalización de esa idea, donde puedes armar una lista infinita a partir de las infinitas listas infinitas asegurándote de que cada elemento de cada lista aparezca al menos una vez.

Te doy un contraejemplo para el case de unión infinita no enumerable de conjuntos finitos o enumerables:
$X = \lbrace \lbrace x \rbrace \mid x \in \mathbb{R} \rbrace$
Cada elemento de $X$ es un conjunto finito (de exactamente un elemento), pero $\mathbb{R} = \cup X$ es infinito no enumerable.
$Y = \lbrace S \mid S \subseteq \mathbb{R} \wedge S \approx \mathbb{N} \rbrace$
Cada elemento de $Y$ es un conjunto enumerable pero $\mathbb{R} = \cup Y$ es infinito no enumerable.

Para terminar de responder a la pregunta, ese resultado no lo vimos en clase, así que si lo requirieras en una prueba o tarea, tendrías que demostrarlo.
