### ISSUE TITLE
Justificaciones para "desigualdades convenientes" en pregunta 1.c)

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC1253/IIC1253-2024-1#17]
Desarrollando la pregunta 1.c, llego a una parte donde tengo una expresión que necesito que sea menor que una constante. Por ejemplo, necesitaría usar que $$bx^{4}-3 < 7$$

El problema es que la complejidad de mostrar que esa desigualdad es cierta me tiene atascado, pues requeriría cosas como calcular derivadas muy complejas o usar límites. Sin embargo, graficando mi expresión, claramente veo que cumple que es menor que la constante. 

Entonces me pregunto si es posible argumentar el uso de esta "desigualdad conveniente" simplemente diciendo "al graficar la expresión se ve que es menor que..." o "usando _Wolfram Mathematica_ se obtiene que la expresión es menor que...".

**Comment by mpiavf** [comment]
Hola!
Sí, puedes hacerlo de ese modo, si ocupas un gráfico lo ideal es que se vea para que uno entienda que tienes una base y no es que llegues a eso de la nada, lo mismo pasa si utilizas un software es mejor mencionarlo tal como indicas :D
Saludos

**Comment by mpiavf** [comment]
Hola @Pablo-Gonzalez-Calderon !
Quería agregar a mi respuesta,  por si no quedo tan claro, que el uso de gráficos o software puede ser utilizado como una guía  para encontrar el n0 en este problema y tener una noción para ayudarte, luego la demostración por **inducción** debe ser formal y de manera rigurosa, es decir mostrando todos los pasos y cómo llegas a ellos.
Espero que haya quedado mas claro.
Saludos!
