### ISSUE TITLE
guia i2 pregunta Cardinalidad pregunta 8

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#172]
No nos indican que la funcion $f$ sea inyectiva por lo que podemos tener la funcion $f(x)=0$ por lo que su $f(\mathbb{N}) = \{0\}$ y ese conjunto no es enumerable, por lo que no se puede demostrar el enunciado.
¿es un error de la guia? o ¿que hice mal?

**Comment by Maratripa** [comment]
Todos los conjuntos finitos son numerables, por lo que {0} si es numerable. El razonamiento detrás de esa pregunta es que cualquier subconjunto de los naturales es numerable, y como el conjunto imagen de la funcion son los naturales, el conjunto tiene que ser numerable. 

Lo que hay que hacer es demostrar el caso general de f. Notar que la pregunta pide "demuestre que..." por li que ya tienes el hint de que es verdadero.

**Comment by Utmite** [comment]
¿Entonces los conjuntos finitos también son enumerables? Pues en la clase 17 se nos define enumerable como |A| = |$\mathbb{N}$| y |{0}| no tiene la misma cardanilidad que los naturales

**Comment by emivenezian** [comment]
misma duda

**Comment by Maratripa** [comment]
Lo que se define en las clases son los conjuntos infinitamente numerables, que por lo general son los conjuntos con los que trabajamos en el curso.

La verdad es que por la definición de igual cardinalidad que los naturales, los conjuntos finitos no son numerables, pero reservamos esta categoría (no numerables) para los conjuntos que tienen cardinalidad mayor a los naturales.

Viéndolo de otra forma, podemos decir que un conjunto numerable es tal que le podemos asignar un número natural a cada elemento / poner el conjunto en una lista que podemos indexar.

En esta pregunta en particular, tomamos los conjuntos finitos como numerables. Pero la definición de clases debería decir: "un conjunto **infinito** es numerable cuando tiene la misma cardinalidad que los naturales".

**Comment by emivenezian** [comment]
pero que funcion biyectiva existe entre el {0} y los naturales?

**Comment by Maratripa** [comment]
No existe, por eso esa definición es de los conjuntos _infinitos_ numerables. Todos los conjuntos finitos son numerables, pero no todos los conjuntos numerables son finitos.

**Comment by emivenezian** [comment]
pero dices que el {0} si es numerable, entonces tiene que existir esa biyeccion

**Comment by Maratripa** [comment]
No necesariamente, la definición de clases no está completa. La definición de clases no es un si, y solo si, es solo una implicancia, por lo que no todos los conjuntos numerables tienen una biyeccion a los naturales.

Es decir, un conjunto es numerable **si** tiene una biyeccion a los naturales. No dice que un conjunto tiene una biyeccion a los naturales **si** es numerable. La definición es solo para un lado, por lo que deja abierta la definición de los conjuntos finitos.

**Comment by Maratripa** [comment]
Para efectos de esa pregunta, puedes asumir que todo conjunto finito es trivialmente numerable, ordenas los n elementos en una lista finita y le asignas el índice de cada elemento al elemento, por lo tanto, los puedes "enumerar".
