### ISSUE TITLE
Explicación Ecuación del inciso (a)

### ISSUE THREAD

**Issue by lietril** [IIC1253/IIC1253-2024-1#18]
![IMG_20240318_110832](https://github.com/IIC1253/IIC1253-2024-1/assets/162619221/281c5ea8-3b0d-4165-90e0-1048bee05a8e)
Hola, quería preguntar si era posible que nos explicaran un poco más sobre cómo funciona la ecuación  (_por ejemplo, si a F(m + 1) se le suma 1 por el +1 del F inicial)_, ¿o es algo que tenemos que determinar a partir de la inducción?. Gracias !!

**Comment by sopadeoliva** [comment]
Hola!
En este inciso se pide que muestren por inducción tal ecuación. F(n) simplemente indica el n-ésimo término de la sucesión de Fibonacci.
Recuerda que F(n) se determina a partir de la suma de los dos términos anteriores, F(n-1) y F(n-2). Y ojo que F(n+1) no es lo mismo que F(n)+1.  Por ejemplo, si tienes F(5) = 5 (el quinto término de la sucesión es 5), pero F(5+1) = 8 (el sexto término es 8), ya que F(6) =F(5) + F(4) = 5 + 3.

Avísame si eso contestó tu pregunta, mucho éxito ⭐
