### ISSUE TITLE
(a) Duda con la definicion de F(m+n+1)

### ISSUE THREAD

**Issue by tremendapithon** [IIC1253/IIC1253-2024-1#19]
Hola buenas tardes, tengo una duda respecto a si puedo definir F(m+n+1) = F(m+n) + F(m+n-1).

Saludos

**Comment by sopadeoliva** [comment]
Hola!

Efectivamente, así se define Fibonacci, F(n+1) = F(n) + F(n-1) para n>0. Necesitas usar esta definición dentro de la inducción para tu demostración. Como dices, mientras n (todo lo de dentro del paréntesis) sea un natural, sabes que se cumple lo anterior.

Mucho éxito ⭐

**Comment by tremendapithon** [comment]
Entonces, si por ejemplo tengo que F(m+n), yo puedo hacer que F(m + (n-1) + 1) = F(m)F(n-1) + F(m+1)F(n), ya que sigue la misma forma de dicha formula, y ademas con (n-1)+1 no altero nada.

Saludos

**Comment by fvaldes17** [comment]
En efecto, si puedes. Eso surge directamente de desarrollar la igualdad que se pide demostrar: F(m + k + 1). Pero considerando k = n - 1.

Ánimo! 🤓

**Comment by tremendapithon** [comment]
Gracias ❤️
