### ISSUE TITLE
Uso de resoluciones de clases 

### ISSUE THREAD

**Issue by Yeps3nM** [IIC1253/IIC1253-2024-1#191]
Hola! 
Cuando resuelvo las tareas y uso el desarrollo explícito o muy similar al de otros ejemplos/ejercicios hechos en clases o ayudantías, basta con mencionar el nombre del documento de donde lo saqué o hay que seguir un formato más estricto? 

Muchas gracias :)

**Comment by Anton-Little** [comment]
Hola, puedes poner:
`Como fue visto en ayudantía/clases: "[Insertar teorema aquí]"`

Saludos.
