### ISSUE TITLE
¿Que es un multigrafo?

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#193]
Hola, buenas
No comprendo muy bien lo de $G(V,E,f:V \rightarrow S)$, ¿como se dibujaria?

**Comment by c4ebt** [comment]
Hola!

Intuitivamente, un multigrafo definido por $G = (V, E, f)$ es un grafo que permite múltiples aristas entre dos nodos (de ahí el nombre), esto es, permite aristas paralelas. Veamos esto con un ejemplo: sea $G = (V, E, f)$ un multigrafo tal que
- $V = \\{ v_1, v_2, v_3 \\}$
- $E = \\{ e_1, e_2 \\}$
- $f  = \\{ (e_1, \\{ v_1, v_2 \\}), (e_2, \\{ v_1, v_2 \\}) \\}$

Las aristas son $e_1$ y $e_2$. Notemos, en primer lugar, que ahora las aristas tienen una identidad de por sí, un nombre, más allá de ser simplemente un par de nodos. No se le da mucha importancia a esto en el ramo, pero sí tiene aplicaciones relevantes de índoles diversas en otras áreas.

Por otra parte, vemos que ambas aristas están mappeadas al mismo par de nodos según $f$, es decir, son aristas paralelas. El multigrafo $G$ se ve así:
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/50504998/9c3ef683-970f-4e1f-9d4d-bf360adc25f3)
Incluso podría haber $3, 4$ o $97$ aristas entre $v_1$ y $v_2$. Esa es la esencia de los multigrafos.

Espero que quede más claro :)
