### ISSUE TITLE
Definicion de conexa

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#194]
En clases vimos que un conjunto es conexo si para $a, b \in A$, se cumple que $(a, b) \lor (b, a) \in E$. Sin embargo, en un árbol, las hojas no necesariamente tienen una arista directa a la raíz, lo que podría llevar a pensar que los árboles no son conexos. ¿Cuál es la definición de conexo en el contexto de los árboles?

**Comment by c4ebt** [comment]
Hola!

El término conexo no significa lo mismo en el contexto de relaciones y el de grafos. Decimos que una relación $R \subseteq A \times A$ es conexa si $\forall a, b \in A: R(a, b) \lor R(b, a)$.
Por otra parte, un grafo es conexo si para todo par de vértices $x, y \in V$ existe un camino entre $x$ e $y$. Notemos que este camino puede tener largo mayor a 1, es decir, no tiene que haber una arista entre todo $x$ e $y$ para que el grafo sea conexo. Las componentes conexas de un grafo se definen similarmente: una componente conexa $V'$ es un conjunto de vértices (en otras palabras, un subconjunto de $V$) tal que para todo $x, y \in V'$ existe un camino de $x$ a $y$.

Espero que se entienda mejor :)
