### ISSUE TITLE
Teorema de componentes conexas

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#196]
Hola! no comprendo bien del todo este teorema, en particular el significado de componente conexa ¿es como un subgrafo?

El teorema dice: un grafo G con n vértices y k aristas tiene al menos n-k componentes conexas.

**Comment by c4ebt** [comment]
Hola!

Una componente conexa es parecida a un subgrafo, pero formalmente es un conjunto de vértices. En otras palabras, una componente conexa es un conjunto $V' \subseteq V$ tal que para todo $x, y \in V'$ existe un camino entre $x$ e $y$.

En un grafo con $n$ nodos y sin aristas, como no existe un camino entre ningún par de nodos, hay $n$ componentes conexas distintas. Al agregar una arista, el número de componentes conexas puede disminuir en a lo más $1$. De ahí surge la noción de que al agregar $k$ aristas, el número de componentes conexas disminuye en a lo más $k$, por lo que el número total de componentes conexas es al menos $n - k$.

Espero que se entienda mejor :)
