### ISSUE TITLE
Solución a últimas ayudantías

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#197]
Hola! Estudiando para el examen me encontré con las últimas ayudantías 11, 12, 13 que no tienen solución :(. Las podrían subir por favor :c, de antemano muchas gracias

**Comment by c4ebt** [comment]
Hola!

Gracias por el recordatorio. Acabo de subir las pautas de esas ayudantías. Falta la solución de la pregunta 1 de la ayudantía 12, apenas esté lista subiré de nuevo ese pdf con la solución agregada :)
