### ISSUE TITLE
Temario exámen

### ISSUE THREAD

**Issue by solebravo** [IIC1253/IIC1253-2024-1#199]
Hola, queria saber cual era el temario del exámen, sobre todo hasta que materia entra, saludos.

**Comment by luzmagurzua** [comment]
Hola :) subieron un anuncio en canvas!

**Comment by cicarrasco5** [comment]
Entra toda la materia excepto el teorema chino de restos, durante la mañana se subirá un anuncio a todas las secciones,
Saludos!
