### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by JSalas277** [IIC1253/IIC1253-2024-1#2]
Como van a funcionar las tareas? Van a publicar los templates aquí o en canvas? Y si es aquí entonces la primera tarea era para esta semana o la próxima? Porque no veo en ningún lado alguna tarea 1 como para desarrollarla

**Comment by seba-bug** [comment]
Hola!
Todo el material se publicará en este repositorio y le anuncio correspondiente será por Canvas. Las fechas de las tareas se encuentran disponibles en el programa del curso que se encuentra aquí en el repositorio. La primera tarea será publicada este miércoles 13 junto a sus instrucciones de entrega y formato.
Un abrazo!
