### ISSUE TITLE
duda inciso b)

### ISSUE THREAD

**Issue by matiaraos** [IIC1253/IIC1253-2024-1#20]
Hola buenas, me presento la duda que en la TI cuando tengo el  F((k+1)n) = aF(n), el **a** si contiene un un factor de **k**, esta debe ser en forma de k + 1? o si ya tengo un F(n) multiplicado por cualquier cosa y lo tengo de esa forma ya esta considerado como correcto, independientemente de lo que sea?

**Comment by sopadeoliva** [comment]
Hola!
El **a** en esta pregunta puede ser cualquier natural. Al pedir que se demuestre que existe un **a** tal que F(kn) = aF(n), estamos diciendo, en otras palabras, que F(kn) es múltiplo de F(n), o bien F(kn) es divisible por F(n). Si asumes que existe un **a** para F(kn)=aF(n), por ejemplo, al hacer la inducción podrías demostrar que existirá otro natural **b** F((k+1)n)=bF(n). Este **b** sería como el "cualquier cosa" que dices.
Quizá la issue #14 te ayude.

Mucho éxito :)

**Comment by tremendapithon** [comment]
Cuando hago induccion en la 2b, y quiero ver el HI, es valido decir que con k = 1, F(n) = aF(N), tipo se que a es un existe y este da la posibilidad que sea cualquier a.
