### ISSUE TITLE
Duda pregunta 2.2 ayudantia 10

### ISSUE THREAD

**Issue by Amegonzale** [IIC1253/IIC1253-2024-1#200]
Holaa buenas :3

Tengo una duda de esta pregunta:

<img width="1144" alt="image" src="https://github.com/IIC1253/IIC1253-2024-1/assets/64616076/7892c4c3-bfcb-45aa-8a0e-a25d89936618">

Para la induccion no me esta quedando realmente claro cual es la HI a la que se refieren y cual seria el procedimiento para probar la propiedad, tengo que demostrar que eliminando un nodo del grafo se sigue cumpliendo?? ayua ;-;

<img width="1144" alt="image" src="https://github.com/IIC1253/IIC1253-2024-1/assets/64616076/ee54c00c-6ac7-44ac-8c2e-6ff3e865de1c">

muchas gracias :D

**Comment by Maratripa** [comment]
Hola! Para resolver esta pregunta se realiza inducción sobre la cantidad de nodos en el grafo ```n```, por lo tanto, para la inducción (fuerte) se asume que todos los grafos que tienen menos que ```n``` nodos cumplen la propiedad. Luego en el paso inductivo, siempre se reduce el grafo a uno que tiene menos nodos, para que cumpla con la hipótesis.

**Comment by Amegonzale** [comment]
ahh, entonces es como sacar el nodo para llegar a algo que sabemos para dsps poder descomponer los n en lo que llegamos + algo si es necesario? :0 para demostraciones de grafos normalmente usamos induccion fuerte? muchas gracias <3

**Comment by Amegonzale** [comment]
cerre la issue sin querer xd perdon

**Comment by Maratripa** [comment]
Como siempre, el tipo de inducción que utilizamos siempre depende del ejercicio. En este caso usamos inducción fuerte porque tenemos dos casos, en uno removemos un nodo y en el otro removemos dos.

El argumento de la demostración es que si sacamos nodos controladamente: o no cambia, o sabemos de qué manera cambia. Si no cambia cuando reducimos la cantidad de nodos, se cumple directamente por la hipótesis inductiva. Si cambia, pero sabemos cómo cambia, podemos reducirlo, aplicar la hipótesis inductiva y agregar lo que sacamos.

Eso es lo que se hace en la pauta.

**Comment by Amegonzale** [comment]
oki, ty :D
