### ISSUE TITLE
ciclo euleriano

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#205]
<img width="419" alt="Screenshot 2024-07-06 at 17 49 43" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/93d7b7ad-4cf5-4f62-9213-458a93f98e3f">
Porque G1 y G2 no serian eulerianos? Segun yo si podemos encontrar un ciclo que contiene a todos las aristas y vertices.

**Comment by c4ebt** [comment]
Hola!

No se puede. Recuerda que un ciclo no puede repetir aristas :)
