### ISSUE TITLE
a mod n

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#206]
<img width="632" alt="Screenshot 2024-07-06 at 19 46 27" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/298b7956-5514-48a7-9ad4-f13cac734ff1">
Como pasa de la igualdad 2 a la 3?

**Comment by c4ebt** [comment]
Hola!

Sacar mod 3 dos veces seguidas sin ninguna operación de por medio es redundante. Al procesar el primer mod 3, el número resultante será menor a 3, con lo que aplicar mod 3 nuevamente sin hacer nada antes no tiene ningún efecto, por lo que podemos simplificar uno de los mod.
