### ISSUE TITLE
mcd

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#207]
<img width="689" alt="Screenshot 2024-07-06 at 20 24 13" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/f799af56-198a-4589-bc21-5cfcabb00a1b">
Porque sabemos que  a = k ⋅ b + a mod b ?

**Comment by c4ebt** [comment]
Hola!

Porque cualquier número ($a$) puede ser escrito como su división entera por otro número ($kb$) más el resto de esa división entera ($a \text{ mod } b$).

**Comment by emivenezian** [comment]
Entiendo eso, entonces en este caso k = a/b division entera?

**Comment by c4ebt** [comment]
Exacto :)
