### ISSUE TITLE
Pregunta teoría de números, examen 2022-2

### ISSUE THREAD

**Issue by solebravo** [IIC1253/IIC1253-2024-1#208]
hola! no entiendo porque con la linea destacada con rosado puedo concluir lo destacado con amarillo
![SmartSelect_20240706_200740_Samsung Notes](https://github.com/IIC1253/IIC1253-2024-1/assets/106562597/1a69748f-cf95-4b97-814c-d43289214886)

**Comment by c4ebt** [comment]
Hola!

Digamos $z = a_1 + (-sk)m_1 = a_2 + (tk)m_2$. Se tiene que:
- $a_1 - z = (sk)m_1$ lo que por definición de congruencia módulo $m_1$ implica que $a_1 \equiv z \pmod{m_1}$.
- $a_2 - z = (-tk)m_2$ lo que por definición de congruencia módulo $m_2$ implica que $a_2 \equiv z \pmod{m_2}$.

**Comment by solebravo** [comment]
@c4ebt Gracias! En esa misma linea,  no entiendo cual es la evidencia o las propiedades para saber que a = k*b + a mod b. Puede que sea por algo parecido en verdad, pero no lo logro cachar 
![SmartSelect_20240706_211223_Samsung Notes](https://github.com/IIC1253/IIC1253-2024-1/assets/106562597/8f1edad4-cf4f-462c-809a-4afc3438e16f)
![SmartSelect_20240706_211234_Samsung Notes](https://github.com/IIC1253/IIC1253-2024-1/assets/106562597/db16fdfc-77ec-4a8d-ac93-3e85e2f7c76e)

**Comment by c4ebt** [comment]
Respondí esa duda en [esta issue](https://github.com/IIC1253/IIC1253-2024-1/issues/207#issuecomment-2212101561) :)
