### ISSUE TITLE
Pregunta conceptual equivalencia modulo y MCD

### ISSUE THREAD

**Issue by solebravo** [IIC1253/IIC1253-2024-1#209]
Hola! tenía una duda conceptual sobre si es correcta la siguiente afirmación: si existe MCD(A,B) entonces existe un n tal que existe la relación "A equivalente modulo n a B".

**Comment by c4ebt** [comment]
Hola!

Notemos en primer lugar que $MCD(A, B)$ siempre existe, ya que el $1$ divide a todos los números enteros.
Por otra parte, también siempre existe un $n$ tal que se cumple esa relación: nuevamente el $1$ satisface que todos los números enteros son $\equiv 0 \pmod{1}$.

Teniendo esas dos cosas en mente, no me parece correcta la afirmación.
Lo que sí es correcto es que, si $MCD(A, B) = 1$, entonces $A$ tiene inverso módulo $B$, y $B$ tiene inverso módulo $A$.
