### ISSUE TITLE
p2.b t1 Asumir Fibonacci como un natural cualquiera

### ISSUE THREAD

**Issue by k0rval4n** [IIC1253/IIC1253-2024-1#21]
¡Hola!
Escribo consultando que, si sabiendo que x es algún natural, entonces se puede asumir que F(x) también es algún natural (no se su valor, pero sí que Fibonacci siempre retorna naturales). ¿Es necesario demostrar eso, o explicando que por definición Fibonacci siempre devuelve valores naturales es suficiente?

Quedo atento a su respuesta, ¡muchas gracias!

**Comment by sopadeoliva** [comment]
Hola!

Sí, puedes asumir que F(n) es natural para cualquier n natural, eso no es parte de la demostración.

Mucho éxito ⭐
