### ISSUE TITLE
Duda ayudantía

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#210]
En la pregunta 3.2 de la ayudantía de repaso para el examen, no entiendo qué es ese N() ni cómo se llega a esta demostración, me podrían ayudar?
<img width="1283" alt="Captura de pantalla 2024-07-06 a la(s) 21 17 57" src="https://github.com/IIC1253/IIC1253-2024-1/assets/163354972/f6c986f0-1a2c-4be7-8cfa-62cb26f9e2bc">

**Comment by c4ebt** [comment]
Hola!

$N(v)$ representa la vecindad del vértice $v$ en $G$, es decir, es el conjunto de todos los vértices $u \in V$ tal que $(v, u) \in E$. Para ver en más detalle como llegar a la demostración, te recomiendo ver la cápsula de la ayudantía, cuyo link está en el README de la carpeta de soluciones de las ayudantías.
