### ISSUE TITLE
grafos ayudantia

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#211]
<img width="777" alt="Screenshot 2024-07-07 at 10 30 58" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/15751b79-684f-46b2-9665-e8fd158664c5">
No entiendo porque el grado seria 2, que pasa con el grafo que tiene tres vertices y dos estan unidos (como un triangulo menos una arista)

**Comment by c4ebt** [comment]
Hola!

Un vértice de corte tiene grado al menos 2, porque si tuviera grado 1 o 0, al quitarlo no aumenta la cantidad de componentes conexas del grafo: si tiene grado 0 no tiene vecinos, por lo que quitarlo claramente no aumenta la cantidad de componentes conexas, y si tiene grado 1 entonces quitarlo solo le resta 1 a la cantidad de vecinos de su único vecino, con lo que tampoco aumenta la cantidad de componentes conexas del grafo.

En el ejemplo que pones el único vértice de corte es el de grado 2: si lo quitamos la cantidad de componentes conexas aumenta a 2, y si quitamos cualquiera de los otros dos vértices entonces la cantidad de componentes conexas se mantiene constante.
