### ISSUE TITLE
ayudantia 13

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#212]
<img width="820" alt="Screenshot 2024-07-07 at 11 30 51" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/72dc6366-1c45-4443-89f6-10fbcdf2fbcb">
De donde sale la igualdad 4?

**Comment by c4ebt** [comment]
Por lo mismo que [acá](https://github.com/IIC1253/IIC1253-2024-1/issues/207#issuecomment-2212101561) :)
