### ISSUE TITLE
examen 2022 2

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#214]
<img width="1053" alt="Screenshot 2024-07-07 at 14 19 37" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/c52ee467-c2f2-4162-9f45-1957f60b58bb">
Hola, en la primera direccion tengo lo mismo que la pauta, pero no me queda claro como concluyen en el finalmente. 

"Finalmente, como d divide a m1 y a m2 (por ser el maximo comun divisor entre ambos) obtenemos que MCD(m1, m2)|(a1 − a2).

**Comment by c4ebt** [comment]
Hola!

En la última ecuación antes del "finalmente", si dividimos por $d$ a ambos lados, como tanto $m_1$ como $m_2$ son divisibles por d, en el lado derecho queda un número entero, por lo que $\frac{a_1 - a_2}{d}$ también debe ser un número entero, lo que equivale a decir que $d | (a_1 - a_2)$.
