### ISSUE TITLE
grafo examen 2022-1

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#215]
<img width="482" alt="Screenshot 2024-07-07 at 16 06 45" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/a3cb0947-a1de-419b-a9e5-9237cad46647">
Hola, no entiendo varias cosas:
1. Cual es la hipotesis inductiva
2. Porque separamos en esos dos casos. 
3. Porque en cada caso modificamos el grafo y le quitamos algo.
4. Porque en el caso 2 quitamos una arista en vez de un vertice, como en el caso 1?
5. Porque al quitar la arista escriben G' = (V - ec, ...), no deberia ser  = (V, modificacion), ya q en el caso anterior quitanos un vertice y por eso se modifican los vertices, pero aca quitamos una arista, entonces no entiendo porque se verian modificados los vertices. 
Graciass

**Comment by PaulaGrune** [comment]
Hola!
1. La hipótesis inductiva es asumir que para todo grafo con n vértices se cumplirá que para toda k-coloración de aristas, un mismo color puede ser usado en a lo más |V|/2 aristas.
2. Es necesario dividir en dos casos ya que hay que evaluar si el vértice añadido en el paso inductivo tiene aristas del color que estamos evaluando (caso 2) o si no tiene ninguna (caso 1)
3. Le quitamos algo para evaluar el caso para n vértices, es decir, vemos qué pasa si le quitamos el vertice que añadimos en el paso inductivo y cómo esto afecta al caso n + 1
4. En el caso 2 también se elimina ec del conjunto de vértices, para hacer el mismo análisis de qué pasa en el caso n y cómo este afecta al caso n + 1
5. Ya que para eliminar la arista es necesario eliminar los vértices que la componían, para que sea válida la comparación
Si no quedó tan claro no dudes en preguntar denuevo :)
