### ISSUE TITLE
Duda pregunta 4.1 ayudantia 13

### ISSUE THREAD

**Issue by Amegonzale** [IIC1253/IIC1253-2024-1#216]
Hola buenas, 
una pregunta no entiendo de donde asumimos que x e y son enteros 
<img width="837" alt="image" src="https://github.com/IIC1253/IIC1253-2024-1/assets/64616076/5dda80c8-fc46-4a9c-9c3d-6243da8545a0">
me hace sentido si lo analizamos del otro lado, pero como se que son necesariamente enteros si busco demostrar que d divide a c. Que ax + by = c puede tener soluciones no enteras ;-; ayuda, gracias!

**Comment by c4ebt** [comment]
Hola!

Faltó explicitarlo en el enunciado, pero al decir que la ecuación tiene solución se quiere decir que _tiene solución en_ $\mathbb{Z}$. La idea era deducirlo por el contexto, pero hubiera sido mejor haberlo puesto en el enunciado para evitar confusiones.
