### ISSUE TITLE
examen 2018 2 divisibilidad

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#217]
<img width="1207" alt="Screenshot 2024-07-07 at 18 41 36" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/1a0d5cbf-0be5-4519-8c07-193cd8d35855">
Creo que falta una multipliacion de mod 3 de la tercera a la cuarta igualdad. Ya q la propiedad multiplica cada factor por mod 3, y ademas toda la expresion completa. Se hizo el mismo ejercicio en clases y alli se considero ese mod 3. 
<img width="436" alt="Screenshot 2024-07-07 at 18 43 21" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/410cfd88-145c-4364-a093-939da2af57f4">

**Comment by c4ebt** [comment]
Hola!

Efectivamente si se quisiera haber usado la propiedad de multiplicación bajo mod habría que poner un mod 3 adicional en la cuarta igualdad.

Sin embargo, notemos que ese mod 3 habría actuado sobre términos que se están sumando, y afuera del paréntesis grande también hay un mod 3, por lo que una forma de verlo es que ese mod 3 no se escribe por hacer la propiedad de adición bajo mod pero "inversa": teníamos que $(a + b) \mod n = (a \mod n + b \mod n) \mod n$, por lo que lo que se hace ahí es como ir de derecha a izquierda en esta propiedad.

De todas formas, haber puesto el mod explícitamente está correcto y hubiera sido lo más intuitivo para esa demostración.

Espero que se haya entendido mejor :)
