### ISSUE TITLE
Duda Casos Base

### ISSUE THREAD

**Issue by sbarriag** [IIC1253/IIC1253-2024-1#22]
Hola tengo una duda que aplica en general para cualquier inducción, que pasa si tengo una propiedad que tiene 3 variables por ejemplo, por lo que requiere 3 casos bases, sin embargo si yo me quiero ir a la segura por decirlo así y hago 4 o 5 casos bases dentro de los cuales están los valores mínimos necesarios para que la inducción funcione, estaria malo? o solo estaría haciendo trabajo de más. Porque en el peor de los casos esas bases extra ya estarian cubiertas por la tesis inductiva no? 

Muchas gracias

**Comment by Maratripa** [comment]
Hola! No estaría malo, puedes demostrar cuantos casos quieras, pero si estarías haciendo trabajo de más. 
A veces incluso puede servir demostrar más casos base de los necesarios para encontrar algún patrón y luego usar solo 1, 2, 3... para la demostración.

**Comment by sofiacorreabusquets** [comment]
gracias @Maratripa ! hay alguna cantidad de casos que se considere generalmente suficientes para mostrar que encontré un patrón válido? gracias de antemano :)

**Comment by pibahamondesw** [comment]
@sofiacorreabusquets usualmente es suficiente algo que cubra los casos base de tu estructura inductiva (ej. el 0 para los naturales, los primeros dos números de Fibonacci, ...) o los suficientes para alcanzar a cumplir una desigualdad o propiedad necesaria para tu demostración del paso inductivo (ej. si quieres demostrar que cierta desigualdad en función de n se cumple, reemplazándola por una más estricta y quizás más limpia que te ayuda con el álgebra, pero que es solo válida para valores más altos de n). Como dijo Martín más arriba, puede ser útil de todas formas probar con más casos, sin necesariamente incluirlos formalmente en la demostración, para encontrar un patrón que es el que te permitirá "desbloquear" el paso inductivo.
