### ISSUE TITLE
p2 b)

### ISSUE THREAD

**Issue by blampasona18** [IIC1253/IIC1253-2024-1#25]
Hola, estaría bien demostrado decir que F(kn-1) es un natural para cualquier valor de k y por lo tanto que es "equivalente" a un b? O es necesario demostrar que es constante para decir que equivale a un b?
Saludos

**Comment by sopadeoliva** [comment]
Hola!

Efectivamente, la función F(n) siempre retorna valores naturales para n >=0, así que si dices b=F(kn-1) es natural está bien para k mayor o igual a 1. (Asumiendo que n no es 0, pero no te estreses por el caso límite)

Saludos! Mucho éxito 🌻

**Comment by blampasona18** [comment]
Buenísimo muchas gracias!
