### ISSUE TITLE
Cambio de nombre al subir archivo a Canvas.

### ISSUE THREAD

**Issue by bozziuc** [IIC1253/IIC1253-2024-1#26]
Buenos días. Luego de haber subido mis archivos a Canvas, hice una modificación y los subí nuevamente. Pero ahora en los nombres de los archivos de entrega apareció un "-1" (en mi computador no presentan ese -1). Lo intenté de nuevo y ahora aparecen con un "-2". ¿Cómo puedo arreglarlo?

**Comment by bozziuc** [comment]
por ejemplo, mi archivo pdf aparece con el nombre numalumno-2.pdf (no sé si puedo incluir mi número de alumno en este foro)

**Comment by cicarrasco5** [comment]
No hay problema en esos casos, ocurre debido a una nueva entrega y no se descontará por eso!
