### ISSUE TITLE
Chatgpt para código Latex

### ISSUE THREAD

**Issue by lietril** [IIC1253/IIC1253-2024-1#27]
Holii, quería preguntar si está permitido usar Chatgpt para ver cómo se hace algo en Latex.
Por ejemplo, yo para referenciar a una página web le pregunté a chatgpt cómo se hacía y me creó una nota de pie con el link. Que yo sepa no es un problema pero mejor prevenir que lamentar jiji

**Comment by cicarrasco5** [comment]
Hola, no hay problema en que utilicen herramientas de inteligencia artificial mientras que las citen correctamente y las sepan utilizar bajo su propio riesgo en caso de que consulten materia o desarrollo de ejercicios.
Saludos!
