### ISSUE TITLE
Nombre del archivo a entregar Tarea 1

### ISSUE THREAD

**Issue by bugfly1** [IIC1253/IIC1253-2024-1#28]
Disculpen la pregunta tonta
El enunciado dice que hay que llamarlos numalumno.pdf y zip, pero ¿eso es literal o tenemos que cambiarlo por nuestro numero de alumno?

Pregunto si deberia llamarse algo como 123456789.pdf o simplemente numalumno.pdf

**Comment by cicarrasco5** [comment]
Debe tener como nombre tu número de alumno!

**Comment by emivenezian** [comment]
Holaaa, yo entendi que tenia que ser numalumno.pdf, por lo que lo mande asi. Va a haber algun problema con eso?

**Comment by cicarrasco5** [comment]
Hola, no cumplir con alguna de las instrucciones de a tarea considera un descuento de 5 décimas.
