### ISSUE TITLE
Sobre la T2

### ISSUE THREAD

**Issue by tremendapithon** [IIC1253/IIC1253-2024-1#29]
Hola buenas tardes tengo una consulta respecto a las fechas de la tarea n*2 de iic1253, debido que el 28 de marzo hay "suspension de actividades académicas", el 29 y 30 ("feriado legal"), por lo que no, se debería extender el plazo de entrega producto del fin de semana largo y de los feriados presentes. 

Saludos

**Comment by cicarrasco5** [comment]
Hola!
Lo consideraremos como equipo docente y se anunciará el nuevo plazo con el enunciado la próxima semana,
Saludos!

**Comment by tremendapithon** [comment]
Muchas gracias
