### ISSUE TITLE
Duda pregunta 1.c

### ISSUE THREAD

**Issue by MystEdu** [IIC1253/IIC1253-2024-1#3]
![pregunta 1_c](https://github.com/IIC1253/IIC1253-2024-1/assets/130402592/e19a6020-dd23-488b-acbc-5db9164b4d18)

Hola
No entiendo el funcionamiento de *k*, ya que si *k* es cualquier natural, podría tener, por ejemplo:
$$100^{100} < 2^{100}$$ lo cual es claramente falso.

**Comment by Anton-Little** [comment]
El problema es encontrar un n desde donde se cumple lo pedido, si bien 100^100 < 2^100 es falso,
1000^100 = 10^300 < 2^1000  = 1.071... * 10 ^ 301 no lo es, (curiosamente por apenitas), y quizas si desde n >= 1000 se cumple lo pedido, entonces tu n0 podría ser 1000.

Me queda la duda si puedo elegir n0 arbitrariamente grande o si tiene que ser el menor que cumpla la restricción.

**Comment by mpiavf** [comment]
Hola! Efectivamente, como se menciona en el comentario anterior, la idea es encontrar el n0 que cumpla con lo pedido, en este caso no se pide que sea el menor, solamente debe cumplir con la restricción y mediante inducción deben demostrar que cumple con lo pedido.
Saludos!

**Comment by juanivegam** [comment]
Entonces el n0 a buscar debe cumplir la desigualdad para cualquier valor que tome k dentro de los naturales?

**Comment by BenzoylMorexide** [comment]
Ya, pero en ese ejemplo que da Anton, si yo llevo k a un número muy grande, entonces se deja de cumplir. Pienso que, incluso eligiendo números gigantes hay problema con que k siga creciendo. Me queda duda porque este problema termina convirtiéndose en algo de pensar en números y crecimientos más rápidos unos con respecto a otros. Como k siempre está creciendo, se vuelve difícil pensar un número específico a partir de cual se cumpla la condición para poder plantear los casos base. ¿Alguna ayuda?

**Comment by Anton-Little** [comment]
Parte con números chicos xd, onda k = 1, k = 2, k = 3 y ve cuál es el valor de n_0, así agarrarás un poquito de intuición sobre el problema =)

**Comment by tremendapithon** [comment]
Pero no se supone que debemos manipular solamente el valor de n_0

**Comment by mpiavf** [comment]
El k va a ser siempre k >= 1. Luego deben buscar el n0 que cumpla con la condición, los métodos que utilicen para encontrar este valor pueden ser variados, lo importante es que se demuestre que se cumpla luego que n^k < 2^n para todo n >= n0, donde el n0 es el valor que definieron ustedes :D

**Comment by martineyz** [comment]
@mpiavf Entonces tiene que cumplirse la desigualdad para todo k >= 1?

**Comment by mpiavf** [comment]
Sí,  por ejemplo, una cosa es utilizar valores de k tal como menciona Anton para tener una idea de qué n0 escoger y otra cosa es que en la demostración (donde ya tenemos un n0 definido ) se cumpla que si  k >= 1 exista n^k < 2^n para todo n >= n0 , ahí buscan caso base y después realizan el paso inductivo.

**Comment by martineyz** [comment]
Hay que explicar como llegamos al n0?

**Comment by seba-bug** [comment]
Hola! Basta con mencionar cómo lo determinaste, es un proceso de inspección entonces es como que lo "soñaste". La parte que nos interesa es la demostración de que es un n0 que cumple lo pedido. Como les comenté en otra issue, el k pensémoslo fijo y que el n0 depende de él., entocnes tu inducción es sobre n>=n0.
Abrazo!

**Comment by tremendapithon** [comment]
Entonces por lo que entiendo el valor de n_0 debe cumplir que n^k < 2^n, tipo si k=3 y n_0 = 10 obtengo que 10^3 < 2^10, y una vez que pueda determinar el valor de n_0 en base a los valores de k, lo que tengo que demostrar es que n>= n_0??

Saludos
