### ISSUE TITLE
Duda problema 2

### ISSUE THREAD

**Issue by cataconi** [IIC1253/IIC1253-2024-1#30]
Hola :D, ¿se puede aplicar el concepto de "máquinas de estados" en la pregunta 2? No lo vimos como tal en clases, pero lo vi en un curso de otro departamento y creo que puede ser útil.

**Comment by seba-bug** [comment]
Hola! Mientras cumplas con lo pedido, no hay problema que en que te inspires en cierto modelo. Lo importante es que construyas fórmulas proposicionales y variables adecuadas.
