### ISSUE TITLE
Pregunta enunciado inciso d

### ISSUE THREAD

**Issue by Amegonzale** [IIC1253/IIC1253-2024-1#31]
Holi buenas, espero que esten teniendo un lindo dia jjj

Tengo una duda, cuando dice "La luz puede tener el mismo color en, a lo más, 3 estados sucesivos", puedo pensar estos estados como intervalos de tiempo? por ejemplo segundos... o estoy entendiendo mal? D:

Muchas gracias n.n

**Comment by seba-bug** [comment]
Hola! En lugar de tiempos en segundos, piénsalo como primer estado, segundo estado, tercer estado, ..., N-ésimo estado. Entonces por ejemplo, el semáforo no puede estar rojo en los estados 6,7,8,9 porque ahí serían 4 estados consecutivos. No sabemos el "tiempo exacto" en el que cambian los colores, entonces nos interesa solo definir estados arbitrarios.

**Comment by Amegonzale** [comment]
Buenos dias! asi queda mas claro, muchas graciass
