### ISSUE TITLE
Duda p1.a

### ISSUE THREAD

**Issue by tremendapithon** [IIC1253/IIC1253-2024-1#33]
Tengo una duda con respecto a lo que piden demostrar, tipo por lo que entiendo es que si $a\in S$ entonces tenemos que demostrar por inducción estructural que "a" es natural o es un string o cadena. Eso no me queda muy claro, ya que cuando haga el BI: tendria que a puede ser ambas.

**Comment by MIrarrazaval** [comment]
Al hacer el BI vas a asumir que todos los elementos pertenecientes al conjunto S<sub>n</sub> pueden o ser un natural o estar encapsulado en comillas. Como no puedes asumir cual es el caso, vas a tener que demostrar que en ambos se cumple la propiedad. Espero que quede resuelta tu pregunta.

**Comment by tremendapithon** [comment]
Ósea, básicamente debo hacer 2 casos bases donde "a" sea natural o donde sea una expresión algebraica, lo cual trivialmente cumpliria, ya que asumimos que a pertenece a S y S tiene elementos natruales o explicaciones algebraicas. Para mi HI, debería asumir que dos elementos cumplen la propiedas para hacer mi paso inductivo o recursivo. Básicamente esa sería la lógica de la pregunta??

**Comment by seba-bug** [comment]
Hola, para enfatizar la idea: las expresiones algebraicas son "fórmulas" de álgebra que no han sido evaluadas para resultar en un número cerrado. Entonces las dejamos "expresadas". ¿Cuáles son las expresiones algebraicas más chicas? El caso base nos dice que son los naturales (todos). Por ejemplo, el número 0 y el número 100 son expresiones algebraicas. El comentario de los strings tiene que ver con que los casos más complejos no se evalúan, sino que se dejan expresados. Por ejemplo, ((0+100)/0) es una expresión algebraica bien construida (a pesar de que sabemos que tiene uan división por cero, pero eso no importa en la definición de S) ¿Se entiende?

**Comment by tremendapithon** [comment]
Entonces a la final eso reduce el caso base a 1, ya que por lo que comenta 0 o 100 es una expresión algebraica como también lo es (0*(100)/0) por dar un ejemplo

**Comment by tremendapithon** [comment]
es una expresión sin "(" y ")", y de ahí para HI debo determinar un a, b en S que cumplen ser expresiones en S??
