### ISSUE TITLE
Duda sobre cómo interpretar en variables los éstados

### ISSUE THREAD

**Issue by Yeps3nM** [IIC1253/IIC1253-2024-1#34]
Hola! 

Estoy confundida respecto a cómo establecer dentro de las variables , los estados. Porque entiendo como se podrían establecer individualmente pero no respecto a la revisión de 3 consecutivos. Es necesario explicar la definición de la variable para 3 y 4 consecutivos? 

Gracias de antemano :)

**Comment by AndreaPGS** [comment]
Hola, quizás te sirva mirar la respuesta de la Issue #31 . La idea es que puedas presentar una fórmula que **para un estado arbitrario** pueda revisar que se cumpla lo que se pide en cada uno de los incisos _b)_, _c)_ y _d)_ (si es necesario revisando los estados que lo anteceden o son posteriores a él).
