### ISSUE TITLE
Posible Error de Enunciado - Pregunta 1 c

### ISSUE THREAD

**Issue by Anton-Little** [IIC1253/IIC1253-2024-1#35]
Hola, en la 1c se pide demostrar que la siguiente desigualdad es siempre cierta (usaré d en vez de depth y L en vez de length)

d(a) <= log_2(L(a))

Pero si tomo esta ecuación:
x = ( ( ( ( (0+1)+2)+3)+4)+5)
Tengo L(x) = 21, log_2(21) = 4.39...
d(x) = 5

y 5 no es menor igual que 4.39.

Quisiera saber si esto es un error de enunciado o si yo estoy interpretando mal las reglas dadas.

**Comment by ibgarrido** [comment]
Hola! lo siento la tardanza. 
El enunciado no posee error, sino que como dices estas interpretando mal las 'reglas'.
En realidad, la profundidad de la expresión que proporcionaste en 4, y no 5 (Recuerda que la función es recursiva y que la profundidad base es 0, por lo que si tienes n números, entonces la profundad de la expresión algebraica  tiene de valor n-1).

**Comment by Anton-Little** [comment]
Hola,

La profundidad de la expresión proporcionada sí es 5:
0 profundidad 0
(0+1) profundidad 1
((0+1)+2) profundidad 2
...
((...)+5) profundidad 5

El enunciado fue actualizado puesto que la propiedad no se cumplía siempre. Ahora la pregunta es encontrar alguna expresión que sí lo cumpla.

Saludos.

**Comment by ibgarrido** [comment]
tienes razón, de hecho se puede modelar como un árbol binario y quedaría:

![Tareas Y Estudio](https://github.com/IIC1253/IIC1253-2024-1/assets/109704360/3e079f1b-95a7-4965-94c7-b20f8e64b112)

Saludos !
