### ISSUE TITLE
Conjunto Naturales 

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC1253/IIC1253-2024-1#36]
Hola, debemos considerar el 0 como parte de los naturales en la pregunta 1?
Saludos :)

**Comment by ibgarrido** [comment]
Hola! Para efectos del curso, el cero se considera parte de los naturales. Ahora bien, recuerda que al hacer inducción podemos partir no necesariamente del cero sino a partir de un valor tal que se empiece a cumplir la propiedad (Eso lo puedes chequear por simple inspección reemplazando valores).

Por ejemplo la siguiente propiedad:
$\forall n \geq 4 n! > 2^n $
