### ISSUE TITLE
Pregunta p2.d

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#37]
La pregunta dice "(d) La luz puede tener el mismo color en, a lo mas, 3 estados sucesivos." puedo asumir que solo puede estar un color prendido a la vez ¿o tambien tengo que tener en cuenta que puede tambien tener rojo y verde al mismo tiempo?

**Comment by Anton-Little** [comment]
+1

**Comment by camiquis** [comment]
Hola!
Pueden asumir que solo puede estar un color encendido
