### ISSUE TITLE
Cuando usar \newpage

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#38]
Las tareas dicen: "cada solucion de cada problema debe comenzar en una nueva hoja. Hint: Utilice newpage" esto se refiere al titulo como Problema 1, Problema 2 o tambien se cuenta como problema los incisos (a), (b), (c)?
Otra pregunta el numalumno.pdf hay que cambiar el numalumno por mi numero de alumno?

**Comment by ibgarrido** [comment]
Hola!, Como recomendación, prioriza la legibilidad para la corrección de los problemas por parte del equipo de ayudantes, y de que tu seas capaz de entender lo que escribiste. Puedes usar newpage por cada pregunta de la tarea (P1 \newpage P2) por ejemplo, pero si te acomoda puedes hacer newpage por cada inciso de cada pregunta.

**Comment by cicarrasco5** [comment]
Hola! Para complementar la respuesta de Ignacio, para evitar descuentos por formato **es obligatorio** hacer \newpage por cada pregunta (1, 2), y no así para cada inciso (a, b, c, i, ii...), lo que no significa que no puedan hacerlo. Y por otra parte efectivamente todo archivo que se llame numalumno debe ser cambiado por su número de alumno.
Saludos!
