### ISSUE TITLE
No existe el inciso p2 (d)

### ISSUE THREAD

**Issue by Anton-Little** [IIC1253/IIC1253-2024-1#40]
El enunciado sugiere:
"Sugerencia: examine los incisos (b), (c) y (d) para determinar qué necesita incluir en su diseño."

Pero la pregunta 2 no consta de inciso (d), pasa del (c) al (e).

¿Falta un inciso adicional o se corrio la alternativa?

**Comment by camiquis** [comment]
Hola
Es un error de tipeo, el e) debería ser d)
