### ISSUE TITLE
Duda 1.b - parentesis

### ISSUE THREAD

**Issue by tomas-jackson** [IIC1253/IIC1253-2024-1#41]
Hola!,

Cuando se describe el operador length, dice que cuenta la cantidad de parentesis.

Esto se refiere a un parentesis entero "()" o simplemente a uno de los extremos "(" 0 ")".

En otras palabras, length("()") = 1 o length("()") = 2?

**Comment by ibgarrido** [comment]
Hola! Notar que  según la definición inductiva del conjunto $S$, los casos bases son los números naturales sin paréntesis

> Si n es natural, entonces n ∈ S.

Por lo que, por ejemplo length(4) = 1.

**Comment by MatiLaB** [comment]
Hola, no me queda claro porque el caso base implicaría que los paréntesis se cuenten en conjunto y no cada uno (yo lo había considerado como que cada uno ( y ) sumaban uno al largo no que en total sumaran 1).
Por ejemplo había considerado que length( (4*3) ) = 5 (como si se contaran los strings que hay)
Tendría que cambiarlo?

**Comment by ibgarrido** [comment]
Si, es 5, debes contar todos los elementos del string.

**Comment by ppvergara** [comment]
Pero podría existir el caso en que la expresión sea (2), que sería length( (2) ) = 3, o en ese caso contaría solo como un natural y sería length( 2 ) = 1?

**Comment by ibgarrido** [comment]
Por la definición del conjunto de las expresiones algebraicas, (2) no debería pertenecer a $S$,ya que el string '(2)' no es de la forma $a=(\psi # \varphi)$ con $\psi, \varphi$ expresiones algebraicas y # un operador aritmético.
