### ISSUE TITLE
Pregunta 2.d, relación con inciso c) y b)

### ISSUE THREAD

**Issue by AntonioEscobar01** [IIC1253/IIC1253-2024-1#42]
Hola ¿Cómo están?, mi duda sobre el inciso d) es si este tiene relación con los incisos de arriba, porque de ser así (y por el funcionamiento que entendemos de un semáforo que es lo que estamos modelando) no hay forma en que en 3 estados consecutivos se repita el mismo color, a menos que se ignoren los incisos anteriores y el funcionamiento que uno entiende de un semáforo.

Espero se entienda la pregunta.

**Comment by dvillas28** [comment]
Como lo interprete yo, SI es que ocurre un cambio de color, este debe ser entre estados sucesivos y debe ser uno de los 3 "cambios de color" permitidos. Pero entre estados sucesivos puede no ocurrir un cambio de color tambien, la unica restriccion es que pueden tener maximo 3 no cambios de color para 3 estados sucesivos

**Comment by camiquis** [comment]
Hola!
Te recomiendo analizarlo considerando que no es mandatorio que entre un estado y otro ocurra un cambio de color
