### ISSUE TITLE
Duda 1.c

### ISSUE THREAD

**Issue by Tichi1010** [IIC1253/IIC1253-2024-1#43]
Hola buenas, mi duda es la siguiente:
En el enunciado pone que "para todo n>= 1 se cumple que existe una expresion algebraica sobre los naturales 'a' pertenece a S"
mi pegunta es si ¿Se puede demortar que existe al menos un 'a' que cumple con lo pedido o tenemos que generalizar para demostrar que se cumple para más de un caso?

**Comment by hctorn** [comment]
Hola! Basta con que demuestres que para todo n>=1 existe al menos una expresión algebraica 'a' sobre los naturales que cumpla con lo solicitado. Es decir, debes demostrar de tal forma que si yo tomo cualquier n>=1 (por ejemplo n=7), hay certeza de que existe al menos una expresión algebraica que cumple con lo que se pide. Avísame si te quedo alguna duda :)

**Comment by Tichi1010** [comment]
okay gracias.
