### ISSUE TITLE
t2 p1 b)

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#44]
hola, para la parte b de esta pregunta, basta con que lo hagamos como los ejemplos de clase? es decir, si nos pidieran definir el operador largo visto en clases sería: 

Largo, recibe lista y entrega numero de elementos (numeros)
∣ ⋅ ∣ ∶ LN → N

1. ∣∅∣ = 0
2. Si L ∈ LN y k ∈ N, entonces ∣L → k∣ = ∣L∣ + 1

no habría que agregarle ningun paso más para la "definición" (ya que no es demostración)?

**Comment by hctorn** [comment]
Hola! Efectivamente. En esta parte solo se pide definir el operador length, por lo que si tu definición de este está completa y es correcta, no necesitas añadir nada más :)
