### ISSUE TITLE
elección conveniente de restricciones

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#45]
Consulta, si yo quiero demostrar que existe un valor o expresión cualquiera que cumpla un cierto requisito (como es el caso de la 1c), puedo manipular "agregando restricciones adicionales" en la parte de la T.I ?? Me explico, si quiero mostrar que para todo n existe un a que cumpla, entonces puedo tomar convenientemente dos a tal que a1>a2 (por ejemplo), o len(a1)<len(a2) ?? Después de todo, si demuestro que se cumple bajo esas restricciones, me quedará un dominio más acotado de a posible, peor sigue siendo cierto que existe un a.

**Comment by Maratripa** [comment]
Hola @fgallard! Si, puedes condicionar las dos variables de la hipótesis entre ellas, siempre y cuando sea una condición que siempre se pueda cumplir.
