### ISSUE TITLE
P2: "Correctitud de la fórmula" para b), c) y d)

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC1253/IIC1253-2024-1#46]
Buenas noches ✨

Leyendo el enunciado previo a los ítems b) c) y d) de la pregunta 2 me surgió la siguiente duda:

Comprendo que en el inciso a) debíamos definir nuestro conjunto de variables proposicionales $P$ tal que nos permitan definir un lenguaje $\mathcal{L}(P)$ de fórmulas proposicionales que deberemos crear en b) c) y d). Sin embargo, me siento un poco confundido cuando se señala:

> Su fórmula debe ser satisfacible si y solo si la propiedad descrita se cumple para un semáforo dado. [...] No necesita demostrar la correctitud de su fórmula

¿Aquí el enunciado está diciendo, informalmente, "dé las fórmulas pero no demuestre la satisfacibilidad"? En otras palabras, ¿no hay que "justificar formalmente" que se cumpla el 'si y solo si' que vimos, por ejemplo, en clases al demostrar que un mapa es 3-coloreable si y solo si es satisfacible?

**Comment by Anton-Little** [comment]
Yo entiendo que debes poner la fórmula, y no una justificación (ej: mediante una tabla de verdad) de si es correcta o no, pero si una explicación de que es lo que esperas que haga.

**Comment by AndreaPGS** [comment]
Exactamente, basta con la fórmula y una descripción de lo que se está evaluando en la fórmula. 
No es necesario demostrar que se satisface, simplemente debe funcionar si se evalúa en un conjunto de estados cualquiera que correspondan a un semáforo que funcione como queremos.
