### ISSUE TITLE
El semáforo puede estar en más de un estado?

### ISSUE THREAD

**Issue by Tichi1010** [IIC1253/IIC1253-2024-1#47]
Hola buenas, revisando los incisos b), c) y d) me di cuenta que en ninguna parte dice que el semáforo no puede estar con más de un color al mismo tiempo en un estado. Por lo menos en el inciso b) en la parte que dice "todo estado es, o verde, roja, o amarilla" no se si conciderar las "o" como disyinciones inclusivas o disyunciones exclusivas.
Mi pregunta es ¿Debo asumir que el semáforo no puede estar con más de un color al mismo tiempo en un estado y por lo tanto agregar a la fórmula que eso no es posible? o ¿Debo asumir que es posible que el semáforo puede estar con más de un color al mismo tiempo en un estado y por lo tanto tambien permitirlo en la fórmula?

**Comment by Anton-Little** [comment]
Hola, me respondieron antes, es un o exclusivo, es decir un color encendido a lo más (y a lo menos también supongo) al mismo estado. Igual que los semaforos en la vida real.

**Comment by camiquis** [comment]
Hola!
Te aconsejo mirar #39

**Comment by Tichi1010** [comment]
Okay gracias,  pero lo del  "o" en el inciso b) debería extrapolarlo a los incisos c) y d) o no es necesario?

**Comment by camiquis** [comment]
Tambien te aconsejo mirar #37
