### ISSUE TITLE
P2.cd

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#48]
Hola, en las partes c y d si es que mi fómula modela la situación, pero puede romper con la condición de b de tener un color por estado, debo agregarle algo al respecto? Lo que pasa es que si juntáramos b,c,d este problema desaparece porque la formula creada en b resuelve que no pueda suceder esta situación, pero no como las preguntas son independientes no sé si hay que volver a agregarlo o se subentiende que el modelo final lo juntaría todo y funcionaría sin problema.

**Comment by AndreaPGS** [comment]
Hola, en total debes entregar una fórmula por inciso (_b, c, d_) que usen las variables proposicionales que definiste en _a_. En efecto, son "independientes" entre sí y se entiende que en el modelo final todas deberían cumplirse si están bien modeladas. Aunque las respuestas a los incisos son independientes entre si, si ya definiste algo puedes volver a usarlo después si sientes que es necesario. Recuerda que se te pide que expliques brevemente el significado de las partes de la fórmula, ahí podrías poner un pequeño _disclaimer_ de lo que explicas en la _Issue_ que está sucediendo, siempre y cuando las fórmulas sigan cumpliendo con lo que se pide en el enunciado.

**Comment by MatiLaB** [comment]
Me queda la duda igual. 
¿Puedo considerar que cada inciso es algo distinto que se debe cumplir independientemente, por ejemplo tomar la instrucción d como única referencia para hacer la formula que se pide, "ignorando" que también nos pidieron el inciso b? 
Esto podría ser parecido a la definición del ejercicio del mapa 3-coloreable, donde se hacían las formulas para cada condición y luego se juntaban para armar el modelo.

¿O, por cada formula que hagamos debemos cumplir todos los incisos anteriores? Siento que de esta forma quedarían formulas muy parecidas unas a otras, si no iguales?
