### ISSUE TITLE
Dudas sobre la revision del inciso 1.d) tarea 2

### ISSUE THREAD

**Issue by bugfly1** [IIC1253/IIC1253-2024-1#49]
¿Existe puntaje parcial o solamente se consigue el punto si funciona perfectamente?
¿La revision sera llevada a cabo con tests o se revisara el archivo manualmente?

**Comment by pibahamondesw** [comment]
Los puntajes parciales quedarán a criterio del corrector o la correctora, quien revisará el archivo manualmente pero que contará con algunos tests a mano para probar la solución en caso de ser necesario
