### ISSUE TITLE
Duda pregunta 1.c 

### ISSUE THREAD

**Issue by Yeps3nM** [IIC1253/IIC1253-2024-1#5]
Hola! La verdad estoy perdida y necesito una pequeña guía en cómo estructurar de forma general la inducción / el propósito de esta pregunta. Gracias!

**Comment by mpiavf** [comment]
Hola!
En esta pregunta debes encontrar un valor n0 de tal forma que se cumpla n^k < 2^n para todo n >= n0 y además k >= 1. Para encontrar este n0 se puede realizar de varias formas, por ejemplo, podrías partir asignando valores que consideres apropiados para ir probando y ver qué conviene más, esta parte ya depende de cada uno. Cuando ya tengas el n0 vas a tener que realizar la demostración por inducción donde buscas el caso base para el cual la afirmación es correcta y después realizas el paso inductivo tal como se vió en clases c:
Si te queda alguna pregunta no dudes en comentar
Saludos!

**Comment by Amegonzale** [comment]
hola :3 y podria definir el n0 como una funcion de k? ono?

**Comment by Amegonzale** [comment]
sii, gracias :DD
