### ISSUE TITLE
Duda P1.b

### ISSUE THREAD

**Issue by Lexiesm** [IIC1253/IIC1253-2024-1#50]
Hola! me queda una duda con a qué se refiere con "defina el operador", esto implica que debemos nosotros crear la implicancia a demostrar  y después demostrarla? (con CB que ya nos lo dan, HI y TI)

Gracias de antemano!

**Comment by MIrarrazaval** [comment]
Hola! Solo se pide una definición de la función. En este caso puedes ocupar el caso base y definir tu propia cláusula inductiva. Tu fórmula debería ser correcta por construcción, así que no es necesario demostrarla por inducción.
