### ISSUE TITLE
T2: Duda exp. alg. a de la pregunta 1.c

### ISSUE THREAD

**Issue by k0rval4n** [IIC1253/IIC1253-2024-1#51]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/141952843/c06f1bb4-948b-4c03-8fe4-c8db1327d7de)

¡Hola! La expresión algebraica mencionada en la proposición de la pregunta 1.c debe cumplir simultáneamente length(a) ≥ n y depth(a) ≤ log2(length(a)), o puedo encontrar un a para length(a) ≥ n y otro a' para depth(a') ≤ log2(length(a'))?

¡Muchas gracias!

**Comment by MIrarrazaval** [comment]
Hola! Para cada n >= 1 tienes que encontrar una única expresión, es decir, no puedes usar dos "a"s distintos para un mismo n.

**Comment by k0rval4n** [comment]
Gracias!

**Comment by BenzoylMorexide** [comment]
Aprovecho esta issue para consultar una cosa que me tiene confundido. Cuando intento hacer la demostración, noto que asumo en H.I que existe un a para n>=1 . Luego, entiendo que, para demostrar que se cumple, entonces debiese encontrar que se cumple para n+1. Mi duda es si está bien pensarlo así. Siento que hay una mezcla entre inducción estructural y fuerte pero creo que es porque no tengo claro el objetivo de mi inducción. ¿Está bien decir que lo que quiero mostrar es que len(a) >= (n+1) ? y se sigue de eso la otra proposición depth(a) <= log2 (length(a))?
Gracias!

**Comment by ibgarrido** [comment]
Hola!
Entiendo tu duda, y la respuesta que te puedo dar es que la elección de qué método de inducción usar es parte del desafío del problema.
Como recomendación adicional recuerda que para inducción estructural trabajamos por capas. Por lo que asumimos que se cumple para la capa S[n] y lo que quieres es probarlo para la capa S[n+1]. (Tal como se hizo en la ayudantía, puedes verla[aquí](https://github.com/IIC1253/IIC1253-2024-1/blob/main/Ayudantias/Soluciones/Ayudantia_2_Solucion.pdf).

En el caso de que quieras resolverlo por inducción fuerte, recuerda que en el paso inductivo asumes que se cumple para todos los casos desde [0,...,n-1] y de ahí pruebas el caso n, usando los casos anteriores.

**Comment by BenzoylMorexide** [comment]
Hola!, tengo una duda con el ejemplo que me diste. ¿Considerarlo desde 0 hasta n-1 sería por conveniencia? Suelo tener en mi cabeza la idea de que inducción fuerte considera la H.I como verdadera para todo k<n. Veo que usar n-1 está dentro de los k, pero como no había visto antes que podría funcionar ocupando n-1, me surgió la duda. También recuerdo que en inducción fuerte debo probar igual para n+1, ¿es así o qué concepto estoy confundiendo? Gracias!

**Comment by ibgarrido** [comment]
Según la definición vista en clases, la inducción fuerte debe cumplir esto: 
<img width="924" alt="Screenshot 2024-04-03 at 4 28 20 PM" src="https://github.com/IIC1253/IIC1253-2024-1/assets/109704360/a275923f-bb89-42f3-87dc-d7260d7bc23a">
