### ISSUE TITLE
Duda cambios entre estados consecutivos 2.c T2

### ISSUE THREAD

**Issue by k0rval4n** [IIC1253/IIC1253-2024-1#52]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/141952843/8fa46df1-4fad-471c-b3c9-49fb8398c095)

El "pueden" de la segunda línea me deja la duda: si por ejemplo en el estado 3 el color era verde, ¿en el estado 4 sí o sí tendrá que ser amarillo? ¿o podría seguir siendo verde en el estado 4, 5, 6, 7, etc y, en el caso que llegase a cambiar, estaría obligado a cambiar solo a amarillo?

¡Gracias!

**Comment by AndreaPGS** [comment]
Hola, no es necesario que siempre que se avance de un estado a otro estado ocurra un cambio de color. Pero si ocurre un cambio de color solo esta permitido que sea entre los colores que dice el enunciado. Ejemplos de lo que esta permitido (_número de estado: color del estado_):
- {..., 3: rojo, 4: rojo, ...}
- {..., 3: rojo, 4: verde, ...}

Ejemplo de algo **no permitido**:
- {..., 3: rojo, 4: amarilla, ...}

**Comment by k0rval4n** [comment]
Super! Muchas gracias! 😁
