### ISSUE TITLE
pregunta 1.c 

### ISSUE THREAD

**Issue by Yeps3nM** [IIC1253/IIC1253-2024-1#54]
Hola!, perdón pero todavía estoy confundida sobre como hacer la parte de la tesis inductiva respecto a las propiedades que se plantean y la hipótesis inductiva. Me quedo estancada en cómo definir lo que probaré y cómo aplicar la HI. 

Muchas gracias :)

**Comment by pibahamondesw** [comment]
Tanto para la inducción simple como para la inducción estructural, siempre la inducción funciona porque la definición de la estructura es inductiva.

1) Tu estructura se define por el menor conjunto que satisface:
- Ciertos elementos base que te das y pertenecen al conjunto
- Reglas constructivas, que te dicen que si tienes ciertos elementos ya en el conjunto, tienes formas de obtener nuevos elementos

2) Tu demostración por inducción estructural va de la mano de la definición:
- Demuestras la propiedad que te interesa para los casos base, que son los elementos base de la definición
- Asumes que la propiedad que te interesa se cumple para ciertos elementos ya en el conjunto, y demuestras que los elementos que puedes construir a partir de las reglas constructivas a partir de esos elementos también cumplen la propiedad
- Concluyes que todos los elementos del conjunto cumplen con la propiedad

La intuición detrás es que como la definición de la estructura es constructiva, con esta demostración muestras que cada vez que "avanzas" en construir un nuevo elemento (n -> n+1 aplicaciones de reglas recursivas) desde los casos base (que también demuestras), cubres que ese nuevo elemento construido cumple con la propiedad.

Espero que te ayude!

**Comment by Yeps3nM** [comment]
Entiendo!! Me ha quedado mucho más claro. Graciass :)
