### ISSUE TITLE
Consulta respecto al inciso D item 2 

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC1253/IIC1253-2024-1#55]
Cuando en la parte d se enuncia que  "La luz puede tener el mismo color en, a lo mas, 3 estados sucesivos."
Esto hace referencia a que un color puede durar fijo a lo más 3 estados ? (ejemplo verde, verde, verde , amarillo.....)
o hace referencia a, cuando dentro del ciclo de colores se puede repetir un color que ya paso por el semaforo ( verde, amarillo, rojo , nuevamente verde)

**Comment by camiquis** [comment]
Hola!
Hace referencia a que un color puede durar fijo a lo mas tres estados, es decir, (verde, verde, verde, amarillo...)
