### ISSUE TITLE
Proposición de fórmulas

### ISSUE THREAD

**Issue by MystEdu** [IIC1253/IIC1253-2024-1#56]
Buenas

Al estar proponiendo una fórmula, ¿puedo establecer una relación entre un estado actual y uno anterior o siguiente?
Por ejemplo: estoy en un estado x y quiero que ese estado cumpla algo en base a un estado (x-1) o (x+1)
¿Es válido hacer esa relación directamente en la fórmula? o ¿debería declarar alguna variable que establezca una relación entre estados?

Gracias de antemano, y que tengan buen día c:

**Comment by AndreaPGS** [comment]
Hola, sí, es válido. Si haces eso recuerda definir bien el conjunto o lista de estados sobre el que trabajaras. También es válido declarar variables que establezcan relaciones entre dos estados, puedes hacerlo de la manera que te parezca mejor, pero mientras este bien modelado no hay problema!

**Comment by rocimarquez** [comment]
Hola, no me queda muy claro que si para definir el conjunto tengo que realizar alguna fórmula especificando que son estados sucesivos o basta con explicarlo.

**Comment by camiquis** [comment]
Hola!
Basta con explicarlo
