### ISSUE TITLE
Sobre suposiciones para la pregunta 2

### ISSUE THREAD

**Issue by dvillas28** [IIC1253/IIC1253-2024-1#57]
Podemos asumir que conocemos todos los estados sucesivos finitos de un semáforo? (algo del tipo la lista de estados A = {1, 2, ... , i, ... , n}) Esto con el proposito de definir las variables proposicionales que necesito mas adelante

Saludos!

**Comment by AndreaPGS** [comment]
Hola, sí, puedes definir la lista de estados como más te convenga.
