### ISSUE TITLE
DUDA 1.C

### ISSUE THREAD

**Issue by tremendapithon** [IIC1253/IIC1253-2024-1#58]
Hola buenas tardes, tengo una duda al momento de demostrar la segunda proposición la de depth(a) <= log_2(length(a)), ya que lo estoy demostrando con inducción estructural y me quedé en la parte donde el TI: depth(a#b) <= log_2 (length(a#b)), ya que asumí que a y b pertenecen a S y cumplen con la propiedad, pero no sé cómo continuar o poder acotar para poder ocupar el HI.

Saludos

**Comment by pibahamondesw** [comment]
No sé si hay algo muy concreto que te puedo decir, pero si eso es lo que te falta supongo que solo puedo recomendar lo obvio, intenta manipular las expresiones que tienes a partir de las definiciones, álgebra y tu hipótesis de inducción.

Saludos!
