### ISSUE TITLE
Consulta sobre formato induccion estructural

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC1253/IIC1253-2024-1#59]
Cuando uno realiza la demostración por inducción estructural, se espera que:
 El caso base, se muestre que en el menor caso cumple.
 En la hipótesis inductiva, hay que suponer que elementos obtenidos de realizar "una vez" el paso recursivo cumplen? o se plantea diciendo que esos elementos base (por ejemplo los que sabemos cumplen el caso base) cumplen la propiedad
 Y luego en la tesis inductiva creamos "nuevos elementos" con el paso recursivo, y se utiliza los caso de la hipótesis en algún punto para reafirmar que los nuevos elementos creados cumplen la propiedad?
 
 Más que nada tengo duda con que se usa en la hipotesis, los menores casos, o algunos cualquiera que se obtuvieron de realizar 1 vez el paso recursivo

**Comment by Maratripa** [comment]
Hola @Sebastian-Assereto! Para la base tienes que usar los elementos iniciales del conjunto, para la hipótesis inductiva, puedes asumir que la propiedad que quieres demostrar para el conjunto se cumple para todos los elementos del conjunto hasta 'n' aplicaciones de la regla recursiva, no solo una vez. 

Luego, para la tesis inductiva tienes que demostrar que la propiedad se cumple para 'n + 1' aplicaciones de la regla recursiva, osea los elementos que se obtienen de aplicar la regla una vez a los elementos que ya cumplen la propiedad.

**Comment by Sebastian-Assereto** [comment]
Valee, muchas gracias

**Comment by tremendapithon** [comment]
Hola,
sí, por ejemplo, quiero demostrar una propiedad sobre el conjunto A y, mi conjunto A tiene como regla de construcción: Si t_1 y t_2 \in S, entonces t_1 operación t_2. Al momento de hacer el HI asumo que la propiedad que quiero demostrar se cumple para algún t_1 y t_2 \in S y cumplen la propiedad del conjunto A. Al hacer TI demuestro la propiedad para t_1 operación t_2 y claramente ahi uso el HI.

**Comment by Maratripa** [comment]
Hola @tremendapithon. Si un conjunto tiene solo dos elementos, no hay que usar inducción para demostrar una propiedad sobre el conjunto.

Para usar inducción estructural, las reglas de construcción del conjunto tienen que ser mínimo 2, una regla base y una regla recursiva. El caso base de la inducción es demostrar la propiedad para los elementos base, la hipótesis inductiva asume que la propiedad se cumple para 'n' aplicaciones de la regla recursiva, y en la tesis se demuestra que se cumple para 'n + 1' aplicaciones.

**Comment by blampasona18** [comment]
Hola @Maratripa me enreda un poco esto para la pergunta 1b). Si el caso base es demostrar la propiedad para los elementos base, entonces estaría mal considerar el caso base length((a#b)) = 1 + 1 + 3 (a,b \in N) ?? Porque los elementos base son pertenecientes a S, no a los naturales

**Comment by gaspargc** [comment]
> Hola @tremendapithon. Si un conjunto tiene solo dos elementos, no hay que usar inducción para demostrar una propiedad sobre el conjunto.
> 
> Para usar inducción estructural, las reglas de construcción del conjunto tienen que ser mínimo 2, una regla base y una regla recursiva. El caso base de la inducción es demostrar la propiedad para los elementos base, la hipótesis inductiva asume que la propiedad se cumple para 'n' aplicaciones de la regla recursiva, y en la tesis se demuestra que se cumple para 'n + 1' aplicaciones.

¿A que se refiere ese "n" aplicaciones? No me queda muy claro... ¿es necesario poner que se cumple para "n" aplicaciones o basta con decir que los elementos cumplen la propiedad porque así lo asumimos...
Gracias!
