### ISSUE TITLE
PREGUNTA 1.C

### ISSUE THREAD

**Issue by tremendapithon** [IIC1253/IIC1253-2024-1#6]
Hola buenas tardes tengo duda a lo solicitado en la parte C, debido que no comprendo donde se remplaza el n_0 en la desigualdad n^k < 2^n, ya que en la desigualdad tenemos n y no n_0.

Además, el valor de k debe ser elegido de forma arbitraria o es k>=1.

Saludos

**Comment by mpiavf** [comment]
Hola
El valor de k siempre va a ser k >= 1. El n0 es el valor que tienen que encontrar de tal modo que se cumpla que **n^k < 2^n para todo n >= n0**. En la desigualdad no tenemos n0 debido a que este último se utiliza en el "para todo".  
Saludos!

**Comment by tremendapithon** [comment]
Entonces debo aplicar induccion respecto a n para verificar la propiedad?

**Comment by tremendapithon** [comment]
Y también el valor de n^k > n_0 o eso no es necesario?

**Comment by BenzoylMorexide** [comment]
Según entiendo debes aplicar inducción una vez ya encuentres el n<sub>0</sub> que cumple la propiedad

**Comment by seba-bug** [comment]
Hola! Para condensar lo que han mencionado. El 1.c tiene dos patitas:

- Misión 1:  para un k arbitrario determinar de alguna forma (por inspección, dibujando las funciones, etc) un n0 adecuado tal que todo n>=n0 cumpla lo pedido. Es decir, el n0 depende del k (dado que el k es fijo, conocido). Si te digo k=4000, me tienes que poder decir cuál es el n0 para ese k. A priori no hay ninguna restricción para ese n0 más allá de que sea natural.
- Misión 2: Demostrar con inducción sobre el n que para n>=n0 se cumple la desigualdad pedida.
¿Se entiende?
