### ISSUE TITLE
Elementos de S

### ISSUE THREAD

**Issue by ymotomy** [IIC1253/IIC1253-2024-1#61]
Hola, tengo una duda sobre los elementos de S. Se puede asumir que con n natural, s peretenciente a S y '#' un operador arbitrario, todos los elementos de S seran solamente del estilo (s#n) (análogamente (n#s)), o también es posible que hayan elementos de la forma (s#s)?

**Comment by ibgarrido** [comment]
Ojo, el conjunto de las expresiones algebraicas $S$, tiene la siguiente definición:

<img width="826" alt="Screenshot 2024-04-03 at 4 42 47 PM" src="https://github.com/IIC1253/IIC1253-2024-1/assets/109704360/104ef3e7-0c71-4825-abd9-dc1837ff4bcf">

Por lo que sí, pueden haber elementos de la forma (S # S).

Por ejemplo: 
![Pdm](https://github.com/IIC1253/IIC1253-2024-1/assets/109704360/3e55c41c-f30d-47c5-9990-dee361daa45e)

Es la expresión algebraica ((2+3)*(5+2))
