### ISSUE TITLE
Pregunta 2, parte d)

### ISSUE THREAD

**Issue by SantiagoOsorio3** [IIC1253/IIC1253-2024-1#62]
Hola, tengo una pregunta en la parte d) de la pregunta 2. En donde el enunciado dice:

 **La luz puede tener el mismo color en, a lo más, 3 estados sucesivos.**

Donde no me queda claro que si es que tengo que sacar una fórmula **solo** para los casos donde las luces son iguales en distintos estados ? o tengo que sacar una fórmula para todos los estados del semáforo, incluyendo esta condición.

También, quería saber si es que los estados parten desde el numero 0 o del 1 ?

Espero que me puedan responder.

Saludos, 

Santiago Osorio.

**Comment by AndreaPGS** [comment]
Hola, los estados pueden partir del 0 o del 1, depende de como los definas tú. Respecto a la otra pregunta, puede servirte revisar issues anteriores, pero la fórmula básicamente debe cumplirse para un semáforo cualquiera que funcione bien (es decir, para cualquier conjunto de estados, tu eliges como modelarlo)
