### ISSUE TITLE
pregunta  2.e

### ISSUE THREAD

**Issue by solebravo** [IIC1253/IIC1253-2024-1#65]
hola! en parte e (o d) de la pregunta 2 piden la formula proposicional  "La luz puede tener el mismo color en, a lo mas, 3 estados sucesivos." Mi pregunta era si en esta prosicion debia agregar que el estado 4 debe ser del color correspondiente o solo negar que sea del mismo color anterior.

Saludos.

**Comment by AndreaPGS** [comment]
Se entiende "a lo más" como el máximo (menor o igual), entonces el máximo son 3 estados sucesivos, más que eso está "mal". Los incisos son independientes, así que basta con negar que no sea el mismo color.
