### ISSUE TITLE
variables entregadas

### ISSUE THREAD

**Issue by Yeps3nM** [IIC1253/IIC1253-2024-1#66]
Hola! 

Tengo la duda en cómo identificar qué variables se inicializan y si siempre debe hacerse, porque en este caso a diferencia del visto en clases del mapa 3 coloreables no dice que se juntaron pares que son o no adyacentes que es de donde se abstrae la inicialización. 

Gracias!

**Comment by AndreaPGS** [comment]
Hola, en esta tarea solo se piden las **fórmulas** que modelan los incisos, no la inicialización.

**Comment by Yeps3nM** [comment]
Entiendo, gracias!!
