### ISSUE TITLE
Duda sobre en Pregunta 1c

### ISSUE THREAD

**Issue by rosarioguerreror** [IIC1253/IIC1253-2024-1#67]
Tengo una pregunta sobre la afirmación en la pregunta 1c. Se nos pide demostrar que D(a) <= log_2(L(a)) para todo n mayor o igual a 1, donde L(a)= length(a) y D(a)= depth(a)

Cuando n es mayor o igual a 21, podemos encontrar expresiones algebraicas con longitud L(a) igual o mayor a 21. Sin embargo, la desigualdad D(a) <= log_2(L(a)) no siempre se cumple.

Por ejemplo, para  L = 21, encontramos que d = 5 , lo que no satisface la desigualdad D(a) <= log_2(L(a)). A medida que L(a) aumenta, como en los casos donde L(a) = 29, 33, 37, 41, la profundidad D(a) también aumenta (a 7, 8, 9, 10 respectivamente), y log_2(L(a)) es menor que D(a), lo que no cumple lo planteado. 

Entonces, parece que para valores de n mayores o iguales a 21, la propiedad no se cumple, ya que D(a) es mayor que log_2(L(a)) en estos casos.

¿Estoy interpretando bien la pregunta?

Gracias!

**Comment by ibgarrido** [comment]
Hola! el enunciado fue modificado hace unos dias. Puedes revisar el actualizado [Aqui](https://github.com/IIC1253/IIC1253-2024-1/blob/main/Tareas/Tarea%202%20Enunciado%20actualizado.pdf)

**Comment by rosarioguerreror** [comment]
Ese es el enunciado que tengo, pero si se debe cumplir para todo n, sucede lo que menciono arriba. Para n>=21 el a definido deberia tener un L(a) mayor o igual a 21 para que se cumpla lo propuesto. Y en esos casos no se cumple que D(a) sea menor que log_2(L(a)). Eso es lo que no me queda claro.

**Comment by hctorn** [comment]
Hola Rosario! Creo que estás interpretando mal el enunciado :( Lo que debemos demostrar es que para cada n>=1 existe un a perteneciente a S que cumple las dos propiedades. En otras palabras, hay que demostrar que para cada n mayor o igual a 1, existe al menos una expresión en el conjunto S que cumple con estas propiedades. Tal y como dices en el caso de n=21, no todas las expresiones van a cumplir con ambas propiedades, sin embargo si para cada n>=1 existe al menos una que cumpla, entonces lo que se propone es cierto. Acá te dejo un ejemplo de una expresión a que cumple con las propiedades para n=21, ya que tiene Lenght(a)=21 y Depth(a)=4, por lo que cumple con D(a) <= log_2(L(a)).

a=((((1+2)+(3+4))+5)+6)

Avísame si te quedó alguna duda :)

Saludos!

**Comment by hctorn** [comment]
Hola! Efectivamente. No se puede demostrar esto con ejemplos particulares, ya que para demostrar que se cumple para todo n>=1, se necesitarían infinitos ejemplos. Es por esto que tal como se menciona en el enunciado, debes utilizar inducción para realizar esta demostración. Avísame si te quedó alguna duda :)

Saludos

**Comment by Yeps3nM** [comment]
Entiendo que no se puede hacer casos particulares y por eso se hace la inducción. Pero si para algunos casos no se cumplen ambas simultáneamente porque depende de cómo se construye en cada caso el a, entonces ahí me entra la duda de como puedo generalizar la fórmula, estoy muy confundida con eso.

**Comment by hctorn** [comment]
Creo que entendí la duda, sorry parece que la interpreté mal antes :(

Cuando realizamos una demostración por inducción, luego de demostrar que la propiedad se cumple para el/los casos base, dejamos de preocuparnos por casos particulares, explicaré esto a continuación. Lo que sigue luego de demostrar el o los casos base es la hipótesis inductiva, en esta parte nosotros hacemos un supuesto de que la propiedad que queremos demostrar se cumple para cierto caso, por ejemplo, si estamos realizando inducción simple, asumimos que la propiedad se cumple para cierto n arbitrario, esto es solamente un supuesto que realizamos.

Luego en la tesis inductiva, utilizamos la HI, es decir, usamos el hecho de que la propiedad se cumple para cierto n, y demostramos que se cumple para n+1, lo anterior se realiza mediante manipulaciones algebraicas de las expresiones de la propiedad, o con otros métodos dependiendo del caso. Es decir, en inducción simple asumes que la propiedad se cumple para un n cualquiera y a partir de ese hecho demuestras que también se cumple para n+1. Esta sería la forma en que se "generaliza", ya que si demostramos que si la propiedad se cumple para n, también se cumple para n+1, por lo que logramos que se cumpla para todos los casos a partir del caso base. Imaginemos que en alguna demostración de inducción simple nuestro caso base es n=0, lo que ya demostramos nos dice que como se cumple para n=0, también se cumple para n=1, y como se cumple para n=1, se cumple para n=2 y así sucesivamente.

Esta explicación fue con inducción simple, la inducción fuerte y la estructural tienen ciertos cambios pero la "esencia" es la misma. Para esta pregunta, según el tipo de inducción que utilices, luego de demostrar que se cumple para el o los casos base solo debes demostrar que si la propiedad se cumple para cierto caso, se cumple también para el siguiente, de esta forma demuestras que se cumple para todos los casos a partir del base.

Perdón por lo largo, ojalá haber entendido la duda y que esto te ayude con como debes hacer la demostración :)

Saludos

**Comment by Yeps3nM** [comment]
Ahora ya lo entendí!! Muchas muchas gracias, me quedó súper claro
