### ISSUE TITLE
consulta respecto al caso base de la C

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC1253/IIC1253-2024-1#68]
una consulta, que no se si se pueda responder o no, pero en la c por enunciado dice 
"Demuestre por induccion que para todo natural n >= 1 se cumple que existe una
expresion algebraica sobre los naturales a S tal que"

mi consulta es dado que queremos demostrar que se cumple para las expresiones algebraicas, el caso base debería ser con una expresion algebraica cualquiera? o un numero natural (el menor caso) tambien se consideraria como "expresion algebraica"

**Comment by ibgarrido** [comment]
Como recordatorio, el menor caso (un número natural) también se considera una expresión algebraica por definición del conjunto $S$.

> si $n$ es natural, entonces $n \in S$
