### ISSUE TITLE
Inicialización variables en problemas de modelación

### ISSUE THREAD

**Issue by jorgee02** [IIC1253/IIC1253-2024-1#69]
Hola! 

Consulta: en los problemas de modelación, es necesario siempre añadir una fórmula que “inicialice” algunas variables ?
 
Por ejemplo las de adyacencia en el mapa 3-coloreable.

Saludos

**Comment by c4ebt** [comment]
Hola!

Sí es necesario añadir una fórmula de esa índole. La razón de esto es que al simplemente declarar variables proposicionales estas no tienen de por si ningún valor o significado. Si no "inicializamos" las variables, podríamos elegir una valuación cualquiera que satisfaga a nuestra fórmula, y como no hay nada que ligue verdaderamente a las variables a nuestro problema, en ese caso el mapa, el escenario es completamente válido y hace que nuestra fórmula no tenga ninguna utilidad.

Te recomiendo revisar [esta issue](https://github.com/IIC1253/IIC1253-2024-1/issues/32), ahí se explicó con más detalle el tema.

Saludos!

**Comment by jorgee02** [comment]
Estupendo! Muy agradecido :) gracias
