### ISSUE TITLE
Pregunta 1.C

### ISSUE THREAD

**Issue by Utmite** [IIC1253/IIC1253-2024-1#7]
Hola buenas!

¿Debo definir mi n_0 en función de k? Por ejemplo n_0 = k
¿Y luego demostrar que eso es cierto para n_0 + 1?

Otra pregunta ¿cómo hay un (n_0+1)^k, ¿Se puede usar el binomio de Newton para demostrarlo mediante inducción?

**Comment by seba-bug** [comment]
Hola!
Exacto, la idea es que si yo te digo k=4000 tú seas capaz de decirme el n0 adecuado (depende de k). Luego, con esa formulita que propongas (que puede ser muy simple), tienes que demostrar por inducción que todo n>=n0 cumple la desigualdad pedida. El k es fijo en ese sentido, arbitrario. El n es la variable de inducción.

Te respondo en un ratito sobre el teo del binomio
Abrazo

**Comment by seba-bug** [comment]
Disculpa la demora, sí puedes usar el teo del binomio!
