### ISSUE TITLE
enunciado 1) a)

### ISSUE THREAD

**Issue by Pancho2301** [IIC1253/IIC1253-2024-1#71]
Hola, no entiendo el enunciado de la pregunta 1) a), en especifico  "entonces o bien a es un natural, o
bien a empieza con “(” y termina con “)”." puede a ser un string de tipo “(” y termina con “)” porque entonces no cumpliría con poder ser una expresión algebraica.

**Comment by hctorn** [comment]
Hola! perdona la demora :(

Ojo que en el enunciado de esta pregunta se menciona que a pertenece a S, por lo que el string "(" no sería un a válido, ya que tal y como dices, esta no es una expresión algebraica, por lo que no pertenece al conjunto S. En resumen, a debe pertenecer si o si al conjunto S, es decir, ser una expresión algebraica que cumple con la definición de este conjunto.

Saludos!
