### ISSUE TITLE
P2A Disclaimers para variables proposicionales

### ISSUE THREAD

**Issue by nicolasaat** [IIC1253/IIC1253-2024-1#72]
Hola! Puedo agregar interpretaciones específicas para algun caso i-n que este fuera de mi rango de estados? Por ejemplo si tengo estados 1, ..., n. ¿Puedo decir que mi variable x_{-1} se evalúa como verdadero/falso porque *explicacion*?

**Comment by camiquis** [comment]
Hola
La idea es que no tengas variables fuera de tu rango de estados
