### ISSUE TITLE
Ayudantia 3 pregunta 4.2.

### ISSUE THREAD

**Issue by Mardones567** [IIC1253/IIC1253-2024-1#73]
![WhatsApp Image 2024-04-07 at 00 34 12_c54fc741](https://github.com/IIC1253/IIC1253-2024-1/assets/111083659/f143c139-646d-4530-9769-6afdb23d216e)

Holaa, espero se encuentren bien.

Tengo una duda sobre si esto seria una respuesta equivalente a la solución de la ayudantia.

Muchas gracias.

**Comment by c4ebt** [comment]
Hola!

Las fórmulas si son equivalentes. Veamos por qué:

- Si $x \not = y$, el lado izquierdo de la implicancia es falso de inmediato, con lo que la subfórmula interior es verdadera trivialmente. Luego, solo interesa el caso en que $x = y$, por lo que podemos prescindir de la variable $y$. Con ello, tenemos que la fórmula es equivalente a $\forall x (R(x) \to \neg C(x, x))$.
- Por ley de implicancia y de De Morgan, se tiene que $\forall x (R(x) \to C(x)) \equiv \forall x (\neg R(x) \lor \neg C(x, x) \equiv \forall x \neg (R(x) \land C(x, x))$.
- Finalmente, por ley de equivalencia de cuantificadores, $\forall x \neg \varphi(x) \equiv \neg \exists x \varphi(x)$. Creo que aún no se ha visto esta propiedad en clases, pero es intuitiva en cierto sentido: si para todo $x$ no se cumple algo, entonces no existe un $x$ tal que se cumpla ese algo.
Aplicando esta ley a la fórmula anterior, $\forall x \neg (R(x) \land C(x, x)) \equiv \neg \exists x (R(x) \land C(x, x))$, que es la fórmula planteada en la pauta.

**Comment by Mardones567** [comment]
Excelente, ahora se como ver si son equivalente, muchas gracias c4ebt.
