### ISSUE TITLE
Duda con pregunta 1 de I1 2021-2

### ISSUE THREAD

**Issue by Mardones567** [IIC1253/IIC1253-2024-1#74]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/111083659/982756c6-3ee3-4cb3-a7e0-d10d86c0edbd)
holaa, espero estén bien.

Si bien entiendo que la demostración de un si y solo si, se hace para ambos lados, aqui veo que lo demuestran directamente desde ambos, ¿es suficiente? o seria adecuado asumir verdadero un lado y llegar al otro y viceversa.

**Comment by PaulaGrune** [comment]
Hola! En este caso están demostrando equivalencia lógica, por lo que no es necesario demostrar ambos lados, con uno basta. En cambio, si necesitas demostrar una doble implicancia ahí sí se debe demostrar ambos lados.
