### ISSUE TITLE
Duda clase 7 modus ponens

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC1253/IIC1253-2024-1#75]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/101026528/43fe9bc8-1b20-4d1e-8a11-29f5a4dbde8c)

Hola! Me surgió una duda con este ejercicio propuesto. Cómo debiese hacer la parte que dice "Demostración por partes"?
Sería como haciendo tablas de verdad y comprobando cada uno por separado? Pero cómo exactamente? 
Gracias!

**Comment by c4ebt** [comment]
Hola!

El ejercicio propone demostrar la regla de inferencia de demostración por partes. Como casi todas las demostraciones, hay más de una forma de hacerlo :)

Una forma podría ser con tablas de verdad. Usar tablas es pertinente porque solo hay 4 variables proposicionales, por lo que habrá 16 filas en la tabla. En mi opinión, a partir de 5 variables ya no vale la pena demostrar por tablas de verdad, pero sigue siendo válido. Otro método que podría funcionar sería demostrar consecuencia mediante el teorema que dice que $\Sigma \models \varphi \leftrightarrow \Sigma \cup$ { $\neg \varphi$ } es inconsistente.

El inicio de una demostración por tablas de verdad podría ser así:
Si vamos a la definición de consecuencia lógica, una fórmula $\varphi$ es consecuencia de un conjunto de fórmulas $\Sigma$ si y solo si para toda valuación $\sigma$ que satisface el conjunto $\Sigma$ se tiene que $\sigma(\varphi) = 1$. Luego, observaremos las tablas de verdad de todas las fórmulas involucradas en $\Sigma$ y $\varphi$, y comprobaremos que para toda valuación tal que $\sigma ( \Sigma ) = 1$ se tiene que $\sigma ( \varphi ) = 1$.

Espero que haya quedado claro. Si no se entendió bien podría hacer la demostración completa, pero recomiendo siempre romperse la cabeza intentando demostrar algo antes de leer una demostración, ya que de lo primero se suele aprender mucho más que de lo segundo :)

**Comment by BenzoylMorexide** [comment]
Muchas gracias!, en el caso de querer demostrar consecuencia mediante el teorema que mencionas, ¿tendría que usar el método de resolución necesariamente? ¿O qué otras formas podría utilizar?
Gracias!
