### ISSUE TITLE
Duda con conjunto funcionalmente completo(ejercicio propuesto)

### ISSUE THREAD

**Issue by Mardones567** [IIC1253/IIC1253-2024-1#76]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/111083659/587ddf70-c273-4803-b4eb-9a8883ff47d5)

Holaa, espero estén bieen.

Tengo una duda sobre este ejercicio propuesto, al intentar hacerlo, primero no encuentro un conjunto de conectivos  C que sea funcionalmente completo para llegar a C' que seria lo que pide el ejercicio. Luego me acerque a la solución pero con el conjunto C = {NOT, AND}, pero al expresar NOT como conectivos de C', me quedan NOT en la expresiones, lo cual seria una muestra que  me falta un paso ya que no lo estoy expresando complemente con conectivo C' o no es conjunto adecuado para demostrarlo.

Muchas gracias.

**Comment by c4ebt** [comment]
Hola!

Tiene sentido que no hayas podido llegar a expresar los conectivos de un conjunto funcionalmente completo con conectivos de $C'$. Spoiler, el conjunto no es funcionalmente completo.

La intuición que hay que tener para llegar a esta conclusión es que es necesario poder expresar todos los conjuntivos de un conjunto funcionalmente completo mediante conectivos del conjunto en cuestión. Si probamos muchas combinaciones y nos damos cuenta de que pase lo que pase no podemos expresar un $\neg$, un $\land$, o un $\lor$, es posible que no sea uno el que la está embarrando al no poder llegar a los conectivos, sino que simplemente no se puede.

Ahora, ¿cómo demostramos que un conjunto no es funcionalmente completo? La idea es distinta a la de demostraciones de f.c., ya que, al menos generalmente, no tenemos "conjuntos no funcionalmente completos" de los cuales podemos partir. Un conjunto no funcionalmente completo sería un conjunto que no puede expresar alguna fórmula. ¿Cómo demostramos esto? Frente a la infinidad de fórmulas existentes, y a la posibilidad de que no es que una fórmula no pueda ser expresada, sino que "nos falta trabajo" para llegar a ella, tenemos que acudir a la mejor herramienta para lidiar con la infinidad en conjuntos definidos inductivamente: inducción :)

Demostrar no-funcionalidad-completa es muy interesante, por lo que recomiendo mucho que intentes hacerlo antes de buscar una solución. Sin embargo, también es difícil si nunca lo has visto antes, por lo que probablemente veremos un ejercicio del estilo en alguna ayudantía próxima. También puedo resolver ese problema en esta issue, pero prefiero dejar un espacio para que lo intentes (o intenten!) antes de mostrar la solución.

Quedo atento para cualquier otra duda :)

**Comment by Mardones567** [comment]
Perfecto, muchas gracias. Voy a intentarlo.
