### ISSUE TITLE
Pautas tareas

### ISSUE THREAD

**Issue by blampasona18** [IIC1253/IIC1253-2024-1#77]
Hola van a subir pautas de las tareas? para poder corregirlas antes de ir al horario de recorrección
Gracias

**Comment by cicarrasco5** [comment]
Hola! Lo siento la demora, ya está arriba la pauta de la T1 y pronto estará la de la T2 para que puedan estudiar para la I1.

**Comment by blampasona18** [comment]
@cicarrasco5 muchas gracias!

**Comment by cgandarillas2** [comment]
Hola! Alcanzarán a subir la pauta de la tarea 2? para estudiar para la I1.
Gracias!

**Comment by cicarrasco5** [comment]
Ya está arriba!
