### ISSUE TITLE
Duda materia sobre satisfacibilidad de predicados

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#78]
Buenas tardes :) tengo una pequeña duda, para saber si estoy entendiendo bien la materia o quizás me esté confundiendo
Si tengo un predicado y me preguntan si éste es satisfacible, necesariamente le debo atribuir una interpretación y si esa interpretación lo hace verdadero, es satisfacible? aunque existan otras interpretacioens que lo hagan falso?

**Comment by PaulaGrune** [comment]
Hola!! Sii, para que un predicado sea satisfacible basta con encontrar una interpretación que lo satisfaga. Pero ojo que en lógica de predicados no se dice que una interpretación "hace falso" algún predicado, sino que esa interpretación no lo satisface. En otras palabras, los predicados no son verdaderos o falsos, sino que son o no satisfacidos por alguna interpretación :)

**Comment by luzmagurzua** [comment]
Gracias por tu respuesta, siguiendo esa misma línea si yo tengo, por ejemplo, un predicado que hace uso de 3 elementos (digamos x,y,z) pero yo noto que la fórmula sólo se cumple para el conjunto {0} por ejemplo, en donde obligatoriamente x=y=z=0 es esto válido para demostrar satisfacibilidad, o necesitaria obligatoriamente los 3 elementos mínimo?

**Comment by PaulaGrune** [comment]
Sí podrías tomar los tres valores igual a 0, es decir, x = y = z = 0, ya que es parte del dominio. Pero depende de la interpretación que le des al predicado para saber si bajo esos valores es satisfacible o no.
