### ISSUE TITLE
T3 P2

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#79]
Holaa 

Consulta sobre la pregunta de predicados, cuando yo simplifico las fórmulas que me entregan me quedan con variables distintas, las simplifiqué igual y llegué a la cláusula vacía sin embargo no sé si mi desarrollo es completamente correcto, puesto que cuando simplifico los cuantificadores quedan los predicados con letras distintas... 

a modo de ejemplo, si yo tengo: 
$\neg D(x, y) \lor \neg G(y) \lor \neg D(x, z) \lor \neg R(z)$

puedo anotarlo como simplemente 
$\neg D(x, y) \lor \neg G(y) \lor \neg R(z)$ ??  ya que la negación de D está dos veces aunque tenga variables distintas? creo que me confunde un poco eso, y quería aclarar... muchas gracias

Otro ejemplo por si no se entiende bien lo que quiero decir: si ese mismo predicado (el resultado que tomé) lo junto con otro que es $D(a,z)$, me quede finalmente como $\neg G(y) \lor \neg R(z)$

**Comment by sopadeoliva** [comment]
Hola!
Así como lo planteas no sería correcto: estos predicados con variables diferentes especificadas no son lo mismo. Igual es muy importante tener en cuenta cuales son los cuantificadores en estas fórmulas: si tus variables no están sujetas a un cuantificador universal/existencial entonces $D(x,y)$ y $D(x,z)$ no son lo mismo. En cambio si tienes, por ejemplo, $\forall x \forall y \forall z \quad D(x,y) \vee D(x,z)$, esta fórmula podría considerarse redundate y podrías simplificarlo a $\forall x \forall y \quad D(x,y)$.
Depende de la situación, pero mucho ojo con eso, fíjate bien si estás perdiendo algo al eliminar una variable cuantificada.
Espero que haya quedado más claro. Mucho éxito! 🐸
