### ISSUE TITLE
Uso de limites

### ISSUE THREAD

**Issue by martineyz** [IIC1253/IIC1253-2024-1#8]
Quería preguntar si está permitido el uso de limites en las demostraciones. Gracias de antemano.

**Comment by seba-bug** [comment]
Hola!
Primero, no necesitan límites para ninguna demostración del curso (ahora ni más adelante). Ahora bien, no quisiera que pongas por aquí qué quieres hacer específicamente con límites, pero ojo que pedimos usar inducción en todos los incisos de esta tarea. Queremos evaluar ese método de demostración (el primero que estudiamos en el curso) y medir cómo usas su estructura. Si gustas puedes escribirle a tu profe de sección para validar por interno.
Abrazo
