### ISSUE TITLE
consecuencia logica 

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#80]
Hola, tengo una pregunta sobre las formulas que son consecuencia logica de un conjunto. Se que una fórmula 
 es consecuencia de un conjunto de fórmulas si y solo si para toda valuación que satisface el conjunto se tiene que esa valuacion tambien satisface a la formula. 
Pero puede pasar por casualidad eso? Es decir, puede que todas las valuaciones q satisfacen al conjunto tambien satisfasgan a la formula y la formula no sea consecuencia logica del conjunto? 
No me queda claro que tiene que ver las valuaciones con ser o no consecuencia logica, se que esa es la definicion pero no entiendo porque. Al final no es que la formula se deduzca o pueda formar a partir del conjunto?

**Comment by PaulaGrune** [comment]
Hola!! Si es que una valuación hace verdadera a un conjunto de formulas ∑ y también hace verdadera a una fórmula φ, φ sí o sí sera consecuencia lógica del conjunto ∑, ya que cumple la definición. No puede pasar que sea sólo casualidad, ya que esta cumpliendo con la definición. Si lo pensamos más abstractamente sin cerrarnos a la definición, podemos decir que podemos deducir φ mediante ∑, ya que si se cumple ∑ se debe cumplir si o si φ. En otras palabras, podemos saber el valor de φ si es que ∑ es verdadero.

**Comment by emivenezian** [comment]
Como? Basta que una valuacion haga verdadera a ∑ para que φ sea consecuencia logica de ∑? Tenia entendido que eso tiene que ser asi para cualquier valuacion, no solo una

**Comment by PaulaGrune** [comment]
Sí! tiene que ser para todas las valuaciones que hagan verdadero a ∑, no solo a una. Me disculpo si se entendió otra cosa :)
