### ISSUE TITLE
[T3] Duda sobre manipulación de formulas al pasarlas a CNF

### ISSUE THREAD

**Issue by Ariimaw** [IIC1253/IIC1253-2024-1#81]
Hola!! :3 En el ítem (b) de la Pregunta 2 estoy transformando las fórmulas de tal forma que me queden solo cositas entre "v"s y tengo las siguientes dudas:

- Si tengo una fórmula con el formato: Existe(x)[ A(x,y) ^ ( B(x) v C(x) ) ] 
Esto lo puedo separar en dos fórmulas independientes como:  1. Existe(x)[ A(x,y) ], 2. Existe(x)( B(x) v C(x) )? Es válido hacer esto para luego, al hacer el método de resolución, instanciarlas cada una por separado?

Mi segunda duda tiene un poco que ver con esto también:

- Si tengo algo de la forma [ A ^ B -> ~(C ^ D)],  es correcto entenderlo como [(A ^  B) -> ~(C ^ D) ]? Ó [ A ^ ( B -> ~(C ^ D) ) ]? Yo siempre he entendido que la implicancia tiene prioridad, así como lo tiene una multiplicación sobre una suma, pero necesito preguntar para estar segura porque es bastante distinto desarrollar la primera manera de verlo a la segunda. 

[ (A ^  B) -> ~(C ^ D) ] lo puedo desarrollar como: [~A v ~B v ~C v ~D]
[ A ^ ( B -> ~(C ^ D) ) ] lo puedo desarrollar como: [A ^ (~B v ~C v ~D)]

Y esta segunda forma de hacerlo me lleva de nuevo a mi primera duda, porque de ser interpretado así entonces yo también dependería de que se pueda hacer el trick que pregunté para poder empezar a resolver, pipipipipi

Apreciaría mucho si alguien me pudiera aclarar esto!!! Muchas gracias de antemano :3

**Comment by sopadeoliva** [comment]
Hola! 

En el primer punto, cuidado. Decir "existe algún x tal que A(x,y) y (B(x) o C(x))" no es necesariamente lo mismo que decir "existe algún x_1 tal que A(x_1,y) y además existe algún x_2 tal que (B(x_2) o C(x_2))", ya que podría ocurrir que, si bien existen x_1 y x_2, nunca sean el mismo valor! (x_1 != x_2). La primera oración asegura que estamos hablando del mismo x para todos los predicados.

Para tu segunda duda, en tu ejemplo el orden correcto sería (A ^ B) -> ~(C ^ D). El orden de precedencia de los operadores lógicos es el siguiente:
1. Negación
2. Conjunción (AND)
3. Disyunción (OR)
4. Implicancia (–>)

Por ejemplo, las siguientes fórmulas serían equivalentes (considera el ~ como negación):
* ~p OR r –> q
* ((~p) OR r) –> q

Puedes encontrar otros ejemplos aquí: https://www.cs.utexas.edu/~dnp/frege/logical-operator-precedence.html

Espero que te haya ayudado! Mucho éxito! 🐸

**Comment by Ariimaw** [comment]
Oh ma gawd comprendo!!!! Me arreglaste la vida, muchisimas gracias!!!!! :3
