### ISSUE TITLE
Ayudantía 4, P2

### ISSUE THREAD

**Issue by blampasona18** [IIC1253/IIC1253-2024-1#82]
Hola!
Tengo una duda en general sobre el método de resolución proposicional en lógica de predicados. Según yo entendía, al usar las reglas de factorización o resolución, no se podían "reutilizar" términos, pero en esta pauta sí lo hacen. Intenté hacerlo sin esto y no me resultó entonces, **se puede efectivamente reutilizar cualquier término con tal de llegar a la cláusula vacía?**
Gracias

**Comment by c4ebt** [comment]
Hola!

Sí se pueden reutilizar términos en el método de resolución.

Sin embargo, la pregunta 2 de la ayudantía 4 también puede ser resuelta sin reutilizar términos. Esto se debe a que la reutilización de un término en más de un paso de resolución es equivalente a un paso de factorización. En el caso de la pregunta 2, se aplica resolución de (4) y (6) y posteriormente resolución de (4) y (9), pero otra opción habría sido hacer resolución de (6) y (9) antes de hacer la resolución de (7); en este paso de resolución te habría quedado un término repetido $(\neg R(a, b))$, por lo que en este punto aplicaríamos la regla de factorización, y posteriormente al aplicar resolución de la expresión resultante con (4) habríamos tenido los mismos resultados que reutilizando un término en dos pasos de resolución.

**Comment by blampasona18** [comment]
Aaaah buenísimo, muchas gracias!
