### ISSUE TITLE
Induccion Estructural para Conjuntos Funcionalmente Completos

### ISSUE THREAD

**Issue by luzmagurzua** [IIC1253/IIC1253-2024-1#83]
![Captura de Pantalla 2024-04-13 a la(s) 15 37 31](https://github.com/IIC1253/IIC1253-2024-1/assets/80796978/e17e836f-4fe7-4db7-ba13-60e114adb3df)

Hola :) en esta pregunta construyen la tabla de verdad siguiente: 
![Captura de Pantalla 2024-04-13 a la(s) 15 39 11](https://github.com/IIC1253/IIC1253-2024-1/assets/80796978/3e2df6b9-aab8-4ce0-a79f-e7f96e0c8abc)

Hay alguna técnica para poder llegar a esa equivalencia lógica? ya que viendo de primera el ejercicio, no sabría como sacar esa conclusión... o simplemente es práctica?:(

**Comment by c4ebt** [comment]
Hola!

No hay una técnica mecánica que te permita llegar a las conclusiones necesarias para la demostración.
Si bien la práctica es algo que puede ayudar en casos como este, lo mejor suele ser estar familiarizado con los conectivos lógicos clásicos y conocer bien sus tablas de verdad para poder identificar en qué situaciones son útiles, y como combinarlos para llegar a expresar otros conectivos.

En general, lo primero que intento al enfrentarme con un ejercicio de demostrar funcionalidad completa es combinar los conectivos del conjunto de distintas maneras para lograr expresar algun otro conectivo clásico, y a medida que voy probando me doy cuenta de que hay algunos que puedo expresar fácilmente y otros que no tanto. A partir de eso, escojo un conjunto adecuado desde el cual partir para demostrar la propiedad, pero considero que es muy importante formarse una intuición de lo que uno puede expresar con los conectivos del conjunto antes de lanzarse a demostrar con un conjunto previo que uno no sabe si va a funcionar.
