### ISSUE TITLE
Duda acerca de manipulación de equivalencias con cuantificadores en lógica de predicados

### ISSUE THREAD

**Issue by rodrigooflores** [IIC1253/IIC1253-2024-1#84]
Hola realizando la pregunta 2 (b) de la tarea 3 me surgieron dos dudas acerca de como se pueden manipular predicados que poseen cuantificadores que no están asociados a su variable. La primera duda es si tengo un predicado que depende de $y$, pero el cuantificador justo depende de $x$, ¿puedo usar la equivalencia asociada al cuantificador de $x$?, como situación de ejemplo propongo lo siguiente: $\neg \exists x (\varphi (y)) \equiv \forall x \neg \varphi (y)$, ¿esto es verdad?, recuerdo que en clases se había dicho que a un predicado se le pueden añadir variables libres como $\varphi (y) \equiv \varphi (y,x)$, pero no sé si aplica en este contexto ¿podría hacer lo mismo para el caso anterior? como: $$\neg \exists x (\varphi (y)) \equiv \neg \exists x (\varphi (y,x)) \equiv \forall x \neg \varphi(y,x) \equiv \forall x \neg \varphi(y)$$
La segunda duda es si a un predicado se le puede agregar cuantificadores de una variable de la que no dependa para poder usar equivalencias, algo como $\exists y \psi(y) \equiv \forall x \exists y \psi(y)$, pregunto porque se me ocurrieron dos situaciones en donde se podría usar: 
$$\forall x \varphi(x) \land \exists y \psi(y) \equiv \forall x \varphi(x) \land \forall x \exists y \psi(y) \equiv \forall x (\varphi(x) \land \exists y \psi(y))$$
o también:
$$\exists x \varphi(x) \lor \exists y \psi(y) \equiv \exists x \varphi(x) \lor \exists x \exists y \psi(y) \equiv \exists x (\varphi(x) \lor \exists y \psi(y))$$ ¿eso es válido?

**Comment by pibahamondesw** [comment]
Sí, de hecho lo expresaste perfectamente!
