### ISSUE TITLE
[T3] Trasladar los cuantificadores en una formula para pasarla a CNF

### ISSUE THREAD

**Issue by dvillas28** [IIC1253/IIC1253-2024-1#85]
En el item (b) al transformar una formula a CNF se me presentó una situación similar a la siguiente

$\forall x \forall y[ P(x) \lor Q(y) \lor \forall z D(z)]$

Dado que la cuantificación de $z$ no esta relacionada con la de $x, y$, ¿la equivalencia se conserva al hacer lo siguiente?

$\equiv \forall x \forall y \forall z[ P(x) \lor Q(y) \lor D(z)]$

Otra cosa, si en vez de un cuantificador universal, fuese un cuantificador existencial ($\exists z$) podría hacer lo mismo y trasladarlo al inicio de la formula?

Gracias de antemano, saludos!

**Comment by pibahamondesw** [comment]
Las respuestas son sí y sí, es posible normalizar las fórmulas a sus formas equivalentes con cuantificadores al inicio. Ojo solamente con que dos cuantificadores pueden usar uso del mismo símbolo para la variable cuantificada, en cuyo caso tendrías que renombrar uno.

Si quieres saber más al respecto, puedes buscar sobre forma normal prenexa (PNF), contenido que también es abordado en el curso de Lógica para ciencia de la computación
