### ISSUE TITLE
ayudantia 3 p4.4

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#86]
la solucion pone ¬∃x.∃y.∃z.(¬(x = y) ∧ ¬(y = z) ∧ ¬(z = x) ∧ C(x, y) ∧ C(y, z) ∧ C(z, x)), pero yo puse ¬∃x.¬∃y.¬∃z.(¬(x = y) ∧ ¬(y = z) ∧ ¬(z = x) ∧ C(x, y) ∧ C(y, z) ∧ C(z, x))
Son equivalentes? Porque solo pusieron que no existe x, yo pense que lo correcto es decir que no existe x, ni y ni z, por eso negue cada existe por separado

**Comment by emivenezian** [comment]
Y esto es lo mismo?
¬∃x.¬∃y. = ¬∃x.∃y.

**Comment by c4ebt** [comment]
Hola!

Esas dos expresiones no son equivalentes. El enunciado nos habla de que no existe (x, y, z) que cumpla una propiedad, por lo que la manera correcta de expresarlo es la negación de la existencia de (x, y, z), lo que se traduce a una negación exterior. Otra forma de pensarlo es que para todo (x, y, z) no se cumple la propiedad, lo que por equivalencia de cuantificadores termina en la negación exterior de los tres cuantificadores existenciales.

Sobre la segunda pregunta, las expresiones no son equivalentes. Pensémoslo de la siguiente manera: la fórmula de la izquierda se puede reescribir como $\neg \exists x \varphi(x)$, con $\varphi(x) = \neg \exists y (\psi)$ y $\psi$ alguna otra fórmula. La de la derecha se podría escribir como $\neg \exists x \varphi'(x)$, con $\varphi'(x) = \exists y (\theta)$. Claramente $\neg \exists y. (\psi)$ no es equivalente a $\exists y . (\psi)$ y de hecho, son fórmulas "opuestas".
