### ISSUE TITLE
Conjunto satisfacible I1 2018 p1

### ISSUE THREAD

**Issue by emivenezian** [IIC1253/IIC1253-2024-1#88]
<img width="1470" alt="Screenshot 2024-04-14 at 11 34 58" src="https://github.com/IIC1253/IIC1253-2024-1/assets/141798472/4c2bab01-6951-439c-b515-46c88e133a13">
Tengo entendido que un una formula propocisional es consecuencia logica de un conjunto de formulas cuando toda valuacion que hace verdadera al conjunto, tambien hace verdadera a la formula.

Entonces para este ejercicio, cuando me dicen que sigma union la negacion de a es inconsitente, yo entiendo que eso quiere decir que existe una valuacion tal que esa valuacion hace verdadera a sigma, pero no hace verdadera a  la negacion de alfa. Es decir, existe una valuacion tal q sigma en esa valuacion es verdadera, y alfa en esa valuacion es verdadera. 

 Pero en el solucionario dicen que 'suponga que Σ ∪ {¬α} es inconsistente. Entonces debemos demostrar que para toda
valuacion v, si Σ(v) = 1 entonces α(v) = 1.' 

Dicen que toda valuacion que hace verdadera a sigma hace falsa a la negacion de alfa, pero yo tengo entendido que para que un conjunto sea inconsistente basta que exista alguna valuacion que haga el conjunto verdadero y la negacion de alfa falsa.

**Comment by PaulaGrune** [comment]
Hola!! Para que el conjunto Sigma unión neg alpha sea inconsistente significa que no existe ninguna valuación que lo satisfaga. Esto puede significar que no exista niguna valuación que satisfaca a Sigma o que no exista ninguna valuación que satisfaga a neg alpha o que no exista ninguna valuación que satisfaga a ambas. Para saber si alpha es consecuencia lógica de sigma, analizamos el caso de que exista una valuación que sí satisfaga a Sigma. Como el conjunto de la unión es inconsistente, esto querría decir que esta valuación no satisface neg alpha, por lo que sí satisface a alpha y por eso es consecuencia lógica de Sigma.

**Comment by emivenezian** [comment]
Osea que Σ ∪ {¬α} es satisfacible si: para toda valuacion, esa valuacion hace verdadero a sigma y a la negacion de alfa. Y Σ ∪ {¬α} es inconsistente si: todas las valuaciones que hacen vd a sigma, hacen falsa a la negacion de alfa? Que pasa si algunas valuaciones hacen vd tanto a sigma como a la negacion de alfa, y otras solo hacen vd a sigma?

**Comment by PaulaGrune** [comment]
Σ ∪ {¬α} es satisfacible si existe una o más valuaciones que hagan al conjunto completo verdadero (basta con una valuación, pero pueden haber más). Si no existe ninguna valuación que haga al conjunto completo verdadero, entonces Σ ∪ {¬α} es inconsistente. Por lo tanto, si es que existe alguna valuación que haga verdadero a Σ, no puede hacer verdadero a {¬α}, porque si lo hiciera, el conjunto sería satisfacible. 
Si no se entendio bien no dudes en preguntar denuevo :)

**Comment by emivenezian** [comment]
Ya la primera parte entendi perfect, pero lo segundo que me dices es lo mismo que te mencionaba la primera vez. "Si no existe ninguna valuación que haga al conjunto completo verdadero, entonces Σ ∪ {¬α} es inconsistente. **Por lo tanto, si es que existe alguna valuación** que haga verdadero a Σ, no puede hacer verdadero a {¬α}, porque si lo hiciera, el conjunto sería satisfacible." 
Eso es lo que hice para resolver el ejercicio, demostre que existe alguna valuacion que hace vd a Σ, pero hace falso a {¬α} es decir, hace vd a. {α}. Pero el solucionario hace lo siguiente:  'suponga que Σ ∪ {¬α} es inconsistente. Entonces debemos demostrar que para toda valuacion v, si Σ(v) = 1 entonces α(v) = 1.' 
No se si me entiendes, pero el solucionario dice que para toda valuacion se tiene que cumplir eso, mientras que lo que me dices y tmb lo que pense yo, es que basta una (existe alguna) valuacion que hace que eso se cumpla.

**Comment by PaulaGrune** [comment]
Entiendo lo que me dices, la confusión está en la diferencia en las definiciones de consecuencia lógica y satisfacibilidad. Para que un conjunto sea satisfacible basta con una sola valuación, pero para que alpha sea consecuencia lógica de Sigma, se debe cumplir la definición para todas las valuaciones que hagan verdadera a Sigma. En todo caso, como en el solucionario lo demuestran con una valuación "cualquiera" esto significa que se cumplira para toda valuación que haga verdadera a Sigma.

**Comment by emivenezian** [comment]
Okey, te sigo con la diferencia de las definiciones. Pero igual me queda la duda de porque hacen, en la segunda direccion, "suponga que Σ ∪ {¬α} es inconsistente. Entonces debemos demostrar que para toda valuacion v, si Σ(v) = 1 entonces α(v) = 1." y no hacen "suponga que Σ ∪ {¬α} es inconsistente. Entonces debemos demostrar que existe alguna valuacion v, tal que si Σ(v) = 1 entonces α(v) = 1."

**Comment by PaulaGrune** [comment]
Ya que queremos demostrar que alpha es consecuencia lógica de Sigma (asumiendo que el conjunto  Σ ∪ {¬α} es inconsistente), por lo que necesitamos que todas las valuaciones que hagan verdad a Sigma hagan verdad a alpha también.

**Comment by emivenezian** [comment]
Entiendo, osea que se refieren al lado derecho de la igualdad, no tiene relacion con que Σ ∪ {¬α} es inconsistente, ese es solo el supuesto. Si se quisiera hacer desde el lado derecho, partiendo de que Σ ∪ {¬α} es inconsistente, deberiamos decir que no existe ninguna valuacion que satisfasga Σ ∪ {¬α} , ya sea por que estas satisfacen a sigma y no a {¬α}, o los 2 casos que mencionaste antes. Solo para corroborar que entendi bien jaja

**Comment by emivenezian** [comment]
Osea esta bien demostrarlo diciendo que como Σ ∪ {¬α} es inconsistente, existe alguna valuacion, tal que esa valuacion satisface a Σ y no satisface a {¬α}, es decir, satisface a {α}? (es, decir, esa valuacion no satisface a Σ ∪ {¬α})? Creo que eso esta bien porque todas las valuaciones no van a satisfacer a  Σ ∪ {¬α}, y es razonable pensar que alguna sera de la forma que satisfasga a Σ y no satisfasga a {¬α}.

**Comment by PaulaGrune** [comment]
Sii estaría bien, pero también podría ocurrir que no existiera niguna valuación que satisfaciera a Sigma, pero en ese caso igual se cumple que alpha es consecuencia lógica, ya que trivialmente cumple la definición
