### ISSUE TITLE
Satisfacibilidad en lógica de predicados

### ISSUE THREAD

**Issue by martineyz** [IIC1253/IIC1253-2024-1#89]
Hola, 

Tengo una duda respecto a que una fórmula sea satisfacible en lógica de predicados. Entiendo que se cumple esta propiedad si esque existe alguna interpretación que hace verdadera a la fórmula. Mi duda es que pasa con una interpretación cuyo dominio sea vacío. Por ejemplo, si tenemos el predicado: 
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/127438338/08dcbc21-5dcf-4208-8b6c-1ce3787663b8)

Esto claramente es una contradicción y no es satisfacible para ninguna interpretación que tenga al menos un elemento en un dominio, pero que pasa si el dominio es vacío?

**Comment by PaulaGrune** [comment]
Hola!! En lógica de predicados los dominios no pueden ser vacíos
