### ISSUE TITLE
Satisfacibilidad dependiendo del elemento que se tome del dominio

### ISSUE THREAD

**Issue by rodrigooflores** [IIC1253/IIC1253-2024-1#90]
Hola, me surgió una duda con respecto a la definición de satisfacibilidad para la semántica de predicados (clase 8 diapositiva 25 de la sección 2) 
![clase8_25_s2](https://github.com/IIC1253/IIC1253-2024-1/assets/141890277/439d333a-45e5-43e5-8f31-664cb2e626ae)
Que $\mathcal{I}$ satisface a $\varphi$ sobre los $a$ ¿significa que la propiedad debe ser verdadera en todo el dominio $\mathcal{I}(dom)$ o solo en algún $a$ del dominio? coloco el siguiente ejemplo del que proviene mi confusión:
Sea el predicado unario $\varphi(x) = \exists y \psi(x,y)$ con dos posibles interpretaciones: $\mathcal{I}_1(dom) =$ { $0,1$ } y el significado de $\psi$ en esta interpretación sea $\mathcal{I}_1(\psi) := (y \neq x)$, y la otra interpretación $\mathcal{I}_2(dom) =$ { $0,1$ } (el mismo dominio), con significado de $\psi$: $\mathcal{I}_2(\psi) := (x+y=2)$. Si analizamos caso por caso en cada interpretación para los $a=x$ pasa lo siguiente:
Para la primera interpretación:
$\quad \varphi(0) = \exists y (y\neq 0) \quad \text{es verdad con }y=1$
$\quad \varphi(1) = \exists y (y\neq 1)\quad \text{es verdad con }y=0$
Pero en el caso de la segunda interpretación:
$\quad \varphi(0) = \exists y (0 + y=2) \text{no es verdad con ningún elemento del domino.}$
$\quad \varphi(1) = \exists y(1+y=2) \text{es verdad con }y=1$
¿Aquí podemos decir que la segunda interpretación $\mathcal{I}_2$ satisface a $\varphi$ porque tiene un $a$ en su dominio que hace verdadera a la fórmula? o ¿solo podemos decir que la primera interpretación $\mathcal{I}_1$ satisface a $\varphi$ porque todos sus $a$ del dominio hacen verdadera a la fórmula?

**Comment by c4ebt** [comment]
Hola!

A diferencia de la lógica proposicional, incluso una vez que otorgas una interpretación a un predicado, este no necesariamente tiene un valor de verdad definido. Si todas las variables del predicado están cuantificadas, entonces el predicado tiene un valor de verdad bajo una interpretación dada. Si hay variables libres, entonces el predicado no tiene un valor de verdad definido, sino que es una función, es decir, $\varphi: \mathcal{I}(dom) \longrightarrow \\{ 0, 1 \\}$, por lo que no es correcto hablar del valor de verdad de un predicado con variables libres.

**Comment by rodrigooflores** [comment]
Gracias, entonces si la función $\varphi: \mathcal{I}(dom) \longrightarrow \{ 0, 1 \}$ toma el valor de $1$ para alguno de sus elementos del dominio ya podemos decir que es satisfacible?
