### ISSUE TITLE
Logica de Predicados

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#92]
En lógica de predicados, específicamente refiriéndome a la pregunta 2 parte 2 de la I1-2017-1, cómo puedo incluir los valores específicos que me piden tomar? (no sé si puedo llegar y meter números al predicado). El ejercicio dice que tenemos que escribir "Para todo par de números primos distintos de 2 y 3 existe un número entre ellos que no es primo", pero no sé como agregar la condición de que sea distintos de 2 y 3. 
Se haría de la siguiente forma?  ∀x ∀y. (¬(x = 2) ∧  ¬ (x = 3) ∧  ¬ (y = 2) ∧  ¬ (y = 3) ∧ P(x) ∧ P(y) -> ∃ z. (x <= z ∧ z <= y ∧ ¬ P(z))
O hay que manipular el dominio de la interpretación y crear como un subdominio que incluya solo los naturales mayores a 3, o algo por el estilo?

<img width="1106" alt="Captura de pantalla 2024-04-14 a la(s) 15 08 24" src="https://github.com/IIC1253/IIC1253-2024-1/assets/163354972/7d465f0d-ed98-438b-95ad-439c1a8d6d68">

**Comment by PaulaGrune** [comment]
Hola!! No se puede agregar numeros al predicado así nomás, ya que serían símbolos que no tienen interpretación. Debes crear un predicado que describa esos números, es decir, que con la interpretación que te dan, ese predicado se satisfaga si su variable es igual al numero.

**Comment by PaulaGrune** [comment]
Creo que el semestre 2022-1 salió un ejercicio parecido en la i1, en github debiese estar la pauta por si lo quieres buscar :)

**Comment by fgallard** [comment]
> Creo que el semestre 2022-1 salió un ejercicio parecido en la i1, en github debiese estar la pauta por si lo quieres buscar :)

vi el ejercicio pero en la pauta no queda muy claro como lo aplica. Cómo sería para este caso??

**Comment by PaulaGrune** [comment]
Puedes partir creando el predicado que describa al cero, por ejemplo C(x, y) := ∃x ∀y x <= y. Este predicado sólo se cumple cuando x = 0. Luego puedes crear el predicado que describa al 1 U(x, y) := ∃x ( ∀y (x <= y ∨ y = C(x, y)) ∧ neg (x = C(x, y)) ). Después hacemos lo mismo para definir el 2 D(x, y) := ∃x ( ∀y (x <= y ∨ y = C(x, y) ∨ y = U(x, y)) ∧ neg (x = C(x, y)) ∧ neg (x = U(x, y)) ). Luego para el 3 sería lo mismo. La idea es crear predicados que sólo se cumplan cuando x es igual al número que necesitamos.

**Comment by PaulaGrune** [comment]
Me acabo de dar cuenta que me equivoqué al definir el predicado, corregido sería así: C(x) := ∀y x <= y, ya que así el x es una variable libre y la y es una variable cuantificada. Repetimos lo mismo para los otros predicados definidos: U(x) := ( ∀y (x <= y ∨ y = C(x)) ∧ neg (x = C(x)) ) y D(x) := ( ∀y (x <= y ∨ y = C(x) ∨ y = U(x)) ∧ neg (x = C(x)) ∧ neg (x = U(x)) ). Igualmente en la ayudantía de hoy veremos otra manera de resolver este ejercicio :)

**Comment by c4ebt** [comment]
Una pequeña corrección a lo anterior, cuando se hace $x = C(x)$ en realidad lo correcto sería simplemente hacer $C(x)$ para el caso en que x es 0. Lo mismo para las otras instancias donde se usa el = incorrectamente, lo correcto es usar el predicado (C(x) o U(x)) sin el igual para los casos en que se quiere checkear si es 0 o 1.
