### ISSUE TITLE
SPDG

### ISSUE THREAD

**Issue by fgallard** [IIC1253/IIC1253-2024-1#93]
<img width="1074" alt="Captura de pantalla 2024-04-14 a la(s) 17 19 43" src="https://github.com/IIC1253/IIC1253-2024-1/assets/163354972/6fd8b680-3f25-42c9-8b01-e305a5654b8a">

En este problema, por qué ocurren los pasos que dicen SPDG?? Por definición para que una interpretación I de una formula f(x) se satisfaga tiene que hacer que la formula f(a) sea verdadera al interpretar cada símbolo de f según I. Pero aquí le está quitando la mitad de la disyunción estableciendo que no hay pérdida de generalidad (spdg). Lo que no entiendo es, por ej, que pasaría si la parte de la disyunción que se me estaba cumpliendo (considerando que al ser un "o", podría ser que el lado izquierdo no se cumpla y el lado derecho sí, y seguiría siendo verdadero) y haciendo la formula verdadera para dicha interpretación hubiese sido justo la parte que se saca?? Cómo no se va a perder generalidad?? O aunque lo que queda no sería cierto en sí mismo, se considera como que satisface a la I inicial por ser parte de la formula original?

**Comment by Mardones567** [comment]
Es sin pérdida de generalidad, osea si tomas el otro caso, se cumpliera igual, al ser una disyunción.

**Comment by c4ebt** [comment]
Hola!

El SPDG se debe a que podríamos haber elegido $\alpha$ o $\beta$ en ese paso y habría dado lo mismo. Es el mismo razonamiento para la primera y la segunda parte, pero lo explicaré con la segunda como ejemplo:

Como se tiene que $\mathcal{I} \models (\exists x \alpha(x)) \lor (\exists x \beta(x))$, podemos decir que $\mathcal{I} \models \exists x (\alpha(x))$ o $\mathcal{I} \models \exists x (\beta(x))$. En cualquiera de los dos casos en la tercera implicancia se podría haber incorporado el otro término y se llegaría a lo deseado de manera correcta, por lo que efectivamente la elección arbitraria de $alpha$ se hace sin pérdida de generalidad.

**Comment by BenzoylMorexide** [comment]
Hola! en este mismo problema, por qué es necesario hacer la especificación existencial con ese "Existe un a"? Luego entiendo que lo "devuelve" con una generalización existencial. No entiendo la necesidad de hacer eso. Gracias!
