### ISSUE TITLE
Consecuencia lógica en predicados

### ISSUE THREAD

**Issue by BenzoylMorexide** [IIC1253/IIC1253-2024-1#94]
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/101026528/fdab4174-9a40-4305-b2c1-c9e5d61b9b59)

Hola, no entiendo cómo pensar estos para dar una respuesta a, por ejemplo, el cuadrado dos y el cuatro. Tengo que dar un dominio y una interpretación a tanto phi como psi, y luego ver si es que la consecuencia lógica se cumple? O dar una interpretación específica con dominio específico es erróneo.  Si es así, ¿por qué? 
Gracias!

**Comment by pibahamondesw** [comment]
Para demostrar que la consecuencia lógica es válida (ejemplos 1 y 3), no basta con dar una interpretación específica, puesto que tienes que mostrar que para toda interpretación I, si I satisface al conjunto (es decir, si I satisface a cada una de sus fórmulas), entonces I satisface a la fórmula. Una interpretación específica no te servirá para eso, pues deben ser todas las interpretaciones. Por lo mismo, para demostrar que la consecuencia lógica NO es válida (casos 2 y 4), basta con un contraejemplo, lo que en este caso corresponde a encontrar una única interpretación específica que satisfaga al conjunto, pero no a la fórmula.
