### ISSUE TITLE
[T3] Diagonales principales

### ISSUE THREAD

**Issue by martineyz** [IIC1253/IIC1253-2024-1#95]
No entiendo bien a que se refiere con **las** diagonales principales en este apartado:
![image](https://github.com/IIC1253/IIC1253-2024-1/assets/127438338/c21b6dbd-abfe-4874-97a0-329a4ee8864d)

¿Se refiere a la diagonal principal de cada subtablero?

**Comment by pibahamondesw** [comment]
No, se refiere a las diagonales del cuadrado grande que conforma el tablero, que también contienen 9 elementos. Se pide que la fórmula asegure que los elementos de cada una de las dos diagonales sean distintos.

**Comment by br0nhg** [comment]
Hola una consulta con respecto a esto, entonces en un dos puntos como (0,0) y en el punto (7,1) que son cada uno de las dos diagonales no pueden tener el mismo valor?
