### ISSUE TITLE
Cómo expresar en CNF el cuantificador existencial

### ISSUE THREAD

**Issue by lcayazzo** [IIC1253/IIC1253-2024-1#97]
Hola!

Tengo una duda acerca de cómo expresar ciertas fórmulas en lógica de predicados en CNF que contienen el cuantificador existencial, como lo es el caso de $\exists x (P(x) \land Q(x))$. Para aplicar resolución, debería convertir $\exists x (P(x) \land Q(x))$ a un conjunto de disyunciones de literales (posiblemente con cuantificadores), pero esto es imposible para la fórmula anterior: una opción sería convertirlo a $\exists x (P(x))$ y $\exists x (Q(x))$, pero al hacer esta transformación se estaría perdiendo información, específicamente el hecho de que es el mismo valor que satisface ambos predicados.

Lo que se me ocurre es que $\exists x (P(x) \land Q(x))$ esté permitido dentro de $\Sigma'$, y que al usar especificación existencial se pueda llegar tanto a $P(a)$ como a $Q(a)$ (con el mismo $a$), pero quiero estar seguro de cuál es el procedimiento esperado, ya que me parece que se rompe la regla de que deberíamos tener clásulas para la resolución.

**Comment by c4ebt** [comment]
Hola!

Te recomiendo revisar [esta respuesta a otra issue](https://github.com/IIC1253/IIC1253-2024-1/issues/91#issuecomment-2054200847).

En resumen, puedes hacer la especificación existencial antes de empezar con la resolución, siempre que respetes conceptualmente su significado, es decir, que no especifiques la variable cuantificada existencialmente a una variable ya especificada.
